const af=()=>globalThis.document?.documentElement?.lang?.startsWith('af');
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export function barChart(title,data,{unit='',maxItems=12,description=''}={}){
  const rows=(data||[]).slice(0,maxItems),max=Math.max(1,...rows.map(x=>Number(x.value)||0)),w=720,left=170,right=55,top=38,rowH=34,h=Math.max(150,top+rows.length*rowH+30),plotW=w-left-right;
  const bars=rows.map((d,i)=>{const y=top+i*rowH,bw=(Number(d.value)||0)/max*plotW;return `<text x="${left-10}" y="${y+18}" text-anchor="end" class="chart-label">${esc(d.label)}</text><rect x="${left}" y="${y+5}" width="${bw}" height="18" rx="4" class="chart-bar"></rect><text x="${Math.min(w-right,left+bw+8)}" y="${y+19}" class="chart-value">${esc(d.value)}${esc(unit)}</text>`;}).join('');
  return `<figure class="viz-card"><figcaption><strong>${esc(title)}</strong>${description?`<span>${esc(description)}</span>`:''}</figcaption><svg class="chart-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}">${bars}</svg>${dataTable(title,rows,unit)}</figure>`;
}
export function lineChart(title,data,{unit='',description=''}={}){
  const rows=data||[],w=720,h=280,left=55,right=25,top=30,bottom=55,pw=w-left-right,ph=h-top-bottom,max=Math.max(1,...rows.map(x=>Number(x.value)||0));
  const pts=rows.map((d,i)=>({x:left+(rows.length<=1?0:i/(rows.length-1))*pw,y:top+ph-(Number(d.value)||0)/max*ph,...d}));const poly=pts.map(p=>`${p.x},${p.y}`).join(' ');
  const labels=pts.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="4" class="chart-point"><title>${esc(p.label)}: ${esc(p.value)}${esc(unit)}</title></circle>${(i===0||i===pts.length-1||i%Math.ceil(Math.max(1,pts.length/6))===0)?`<text x="${p.x}" y="${h-23}" text-anchor="middle" class="chart-label">${esc(p.label)}</text>`:''}`).join('');
  return `<figure class="viz-card"><figcaption><strong>${esc(title)}</strong>${description?`<span>${esc(description)}</span>`:''}</figcaption><svg class="chart-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><line x1="${left}" x2="${left}" y1="${top}" y2="${top+ph}" class="chart-axis"></line><line x1="${left}" x2="${w-right}" y1="${top+ph}" y2="${top+ph}" class="chart-axis"></line><polyline points="${poly}" class="chart-line"></polyline>${labels}</svg>${dataTable(title,rows,unit)}</figure>`;
}
export function matrixChart(title,{bands,matrix,max},description=''){
  return `<figure class="viz-card"><figcaption><strong>${esc(title)}</strong>${description?`<span>${esc(description)}</span>`:''}</figcaption><div class="matrix" role="img" aria-label="${esc(title)}"><div></div>${bands.map(b=>`<strong>${esc(b)}</strong>`).join('')}${matrix.map(r=>`<strong>${esc(r.day)}</strong>${r.values.map(v=>`<span class="matrix-cell" style="--intensity:${Math.max(.08,v/max)}"><b>${v}</b></span>`).join('')}`).join('')}</div><details class="chart-data"><summary>${af()?'Datatabel':'Data table'}</summary><table><thead><tr><th>Day</th>${bands.map(b=>`<th>${esc(b)}</th>`).join('')}</tr></thead><tbody>${matrix.map(r=>`<tr><th>${esc(r.day)}</th>${r.values.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></details></figure>`;
}
function dataTable(title,rows,unit){return `<details class="chart-data"><summary>${af()?'Datatabel':'Data table'} — ${esc(title)}</summary><table><thead><tr><th>${af()?'Kategorie':'Category'}</th><th>${af()?'Waarde':'Value'}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.label)}</td><td>${esc(r.value)}${esc(unit)}</td></tr>`).join('')}</tbody></table></details>`;}
