function csvCell(v){ const s=v==null?'':String(v); return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s; }
function xml(v=''){ return String(v??'').replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c])); }
export function toCSV(rows,columns){ return [columns.join(','),...rows.map(r=>columns.map(c=>csvCell(r[c])).join(','))].join('\n'); }
export function registryCSV(animals,taxa){ return toCSV(animals.map(a=>{ const t=taxa.find(x=>x.id===a.taxon_id)||{}; return {public_id:a.public_id,name:a.name,scientific_name:t.scientific_name||'',common_name:t.common_name_en||'',sex:a.sex,life_stage:a.life_stage,estimated_age_years:a.estimated_age_years,registration_date:a.registration_date,status:a.status}; }),['public_id','name','scientific_name','common_name','sex','life_stage','estimated_age_years','registration_date','status']); }
export function observationCSV(observations){return toCSV((observations||[]).map(o=>({id:o.id,public_id:o.public_id||'',name:o.name||'',observed_at:o.observed_at,latitude:o.lat,longitude:o.lng,gps_accuracy_m:o.accuracy_m??o.gps_accuracy_m??'',behaviour:o.behaviour||'',condition:o.condition||'',verification_status:o.verification_status||'',quality_score:o.quality_score??'',species:o.species_name||o.common_name||''})),['id','public_id','name','observed_at','latitude','longitude','gps_accuracy_m','species','behaviour','condition','verification_status','quality_score']);}
export function observationsGeoJSON(observations){ return JSON.stringify({type:'FeatureCollection',features:(observations||[]).filter(o=>Number.isFinite(Number(o.lat))&&Number.isFinite(Number(o.lng))).map(o=>({type:'Feature',geometry:{type:'Point',coordinates:[Number(o.lng),Number(o.lat)]},properties:{id:o.id,animal_id:o.animal_id,public_id:o.public_id,name:o.name||null,observed_at:o.observed_at,accuracy_m:o.accuracy_m??o.gps_accuracy_m??null,species:o.species_name||o.common_name||null,behaviour:o.behaviour,condition:o.condition,verification_status:o.verification_status,quality_score:o.quality_score}}))},null,2); }
export function observationsKML(observations,{name='Nautilus Bay observations',description='Authorised observation export. Point locations represent recorded observations; no route between points is implied.'}={}){
  const rows=(observations||[]).filter(o=>Number.isFinite(Number(o.lat))&&Number.isFinite(Number(o.lng)));
  const placemarks=rows.map(o=>`<Placemark><name>${xml(o.public_id||o.name||'Observation')}</name><description>${xml(`${o.name||''}${o.species_name?` · ${o.species_name}`:''}${o.condition?` · ${o.condition}`:''}`)}</description><TimeStamp><when>${xml(new Date(o.observed_at).toISOString())}</when></TimeStamp><ExtendedData><Data name="observation_id"><value>${xml(o.id||'')}</value></Data><Data name="animal_id"><value>${xml(o.animal_id||'')}</value></Data><Data name="behaviour"><value>${xml(o.behaviour||'')}</value></Data><Data name="condition"><value>${xml(o.condition||'')}</value></Data><Data name="gps_accuracy_m"><value>${xml(o.accuracy_m??o.gps_accuracy_m??'')}</value></Data><Data name="verification"><value>${xml(o.verification_status||'')}</value></Data><Data name="quality_score"><value>${xml(o.quality_score??'')}</value></Data></ExtendedData><Point><coordinates>${Number(o.lng).toFixed(7)},${Number(o.lat).toFixed(7)},0</coordinates></Point></Placemark>`).join('');
  return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${xml(name)}</name><description>${xml(description)}</description>${placemarks}</Document></kml>`;
}
export function movementKML(observations,{name='Nautilus Bay observed-position connections'}={}){
  const groups={};for(const o of observations||[]){if(!Number.isFinite(Number(o.lat))||!Number.isFinite(Number(o.lng)))continue;(groups[o.public_id||o.animal_id||'UNASSIGNED']??=[]).push(o);}let content='';
  for(const [id,rows] of Object.entries(groups)){rows.sort((a,b)=>new Date(a.observed_at)-new Date(b.observed_at));for(const o of rows)content+=`<Placemark><name>${xml(id)}</name><TimeStamp><when>${xml(new Date(o.observed_at).toISOString())}</when></TimeStamp><Point><coordinates>${Number(o.lng).toFixed(7)},${Number(o.lat).toFixed(7)},0</coordinates></Point></Placemark>`;if(rows.length>1)content+=`<Placemark><name>${xml(id)} — inferred observation connection</name><description>Dashed/straight connection is an analytical visual link between recorded positions, not the actual route travelled.</description><LineString><tessellate>1</tessellate><coordinates>${rows.map(o=>`${Number(o.lng).toFixed(7)},${Number(o.lat).toFixed(7)},0`).join(' ')}</coordinates></LineString></Placemark>`;}
  return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${xml(name)}</name>${content}</Document></kml>`;
}
export function movebankEventCSV(observations,animals){
  const rows=(observations||[]).map(o=>{ const a=animals.find(x=>x.id===o.animal_id); return {'event-id':o.id,'individual-local-identifier':a?.public_id||o.public_id||'UNASSIGNED',timestamp:o.observed_at,'location-long':o.lng,'location-lat':o.lat,'sensor-type':'human observation','horizontal-accuracy':o.accuracy_m??o.gps_accuracy_m??'','comments':`${o.behaviour||''}; ${o.condition||''}`}; });
  return toCSV(rows,['event-id','individual-local-identifier','timestamp','location-long','location-lat','sensor-type','horizontal-accuracy','comments']);
}
export function downloadText(filename,text,type='text/plain'){ const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
