import { tr, getLanguage, setLanguage, locale } from './i18n.js';
import { Repo, isDemo, authApi } from './repository.js';
import { queueSighting, countPending, syncPending } from './offline.js';
import { qualityScore, qualityBand } from './quality.js';
import { track, productEvents } from './analytics.js';
import { registryCSV, observationCSV, observationsGeoJSON, observationsKML, movementKML, movebankEventCSV, downloadText } from './export.js';
import { DemoDB, uuid } from './storage.js';
import { applyObservationFilters, categoryCounts, monthlyCounts, hourBands, qualityBands, lastSeenRows, movementMetrics, observationMatrix, median } from './analysis.js';
import { barChart, lineChart, matrixChart } from './charts.js';
import './performance.js';
import { applyPlatformMode, watchPlatformMode, getCurrentPosition, getCameraStream, stopMediaStream, haptic, share, setupNativeBack, installState } from './platform.js';

const cfg=window.NAUTILUS_CONFIG;
const platform=applyPlatformMode();
watchPlatformMode(()=>{});
const state={role:sessionStorage.getItem('nautilus-role')||null,staffName:sessionStorage.getItem('nautilus-staff-name')||null,lastSubmission:null,installPrompt:null,qrStream:null,modalReturnFocus:null,sightingStep:1};
setLanguage(getLanguage());
track('app_opened',{mode:isDemo()?'demo':'production'});

const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat(locale(),{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'—';
const fmtDate=d=>d?new Intl.DateTimeFormat(locale(),{dateStyle:'medium'}).format(new Date(d)):'—';
const route=()=>((location.hash.slice(1)||'/').split('?')[0]);
const go=p=>location.hash=p;
const query=()=>new URLSearchParams((location.hash.split('?')[1]||''));
const human=v=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const daysAgo=d=>{ if(!d)return'—'; const n=Math.max(0,Math.floor((Date.now()-new Date(d))/86400000)); return n===0?tr('today'):`${n} ${tr('daysAgo')}`; };
const safeImageUrl=u=>{if(!u||typeof u!=='string')return './assets/tortoise-placeholder.svg';try{const x=new URL(u,location.href);return ['https:','http:'].includes(x.protocol)&&(!u.startsWith('http')||x.origin===location.origin||x.hostname.endsWith('.supabase.co'))?x.href:'./assets/tortoise-placeholder.svg';}catch{return './assets/tortoise-placeholder.svg';}};

function mobileMenuLinks(){
  if(route().startsWith('/staff/') && state.role){
    const links=[['dashboard',tr('dashboard')],['insights',tr('insights')],['animals',tr('animals')],['observations',tr('observations')],['health',tr('health')]];
    if(['ranger','researcher','admin'].includes(state.role))links.push(['spatial',tr('mapLab')]);
    if(['researcher','admin'].includes(state.role))links.push(['research',tr('research')],['devices',tr('devices')],['export',tr('exportData')]);
    if(state.role==='admin')links.push(['qr',tr('qrCodes')],['audit',tr('audit')],['settings',tr('settings')]);
    return links.map(([id,label])=>`<a data-nav="/staff/${id}" href="#/staff/${id}">${label}</a>`).join('')+`<a href="#/logout">${tr('logout')}</a>`;
  }
  return `<a data-nav="/directory" href="#/directory">${tr('directory')}</a><a data-nav="/about" href="#/about">${tr('about')}</a><a data-nav="/privacy" href="#/privacy">${tr('privacy')}</a><a data-nav="/login" href="#/login">${tr('staff')}</a>`;
}
function appTabbar(){
  if(route().startsWith('/staff/') && state.role){
    const third=['ranger','researcher','admin'].includes(state.role)?['/staff/spatial','⌖',tr('mapLab')]:['/staff/insights','▥',tr('insights')];
    return `<nav class="app-tabbar" aria-label="${tr('appNavigation')}"><a data-nav="/staff/dashboard" href="#/staff/dashboard"><span aria-hidden="true">⌂</span><b>${tr('dashboard')}</b></a><a data-nav="/staff/animals" href="#/staff/animals"><span aria-hidden="true">🐢</span><b>${tr('animals')}</b></a><a data-nav="${third[0]}" href="#${third[0]}"><span aria-hidden="true">${third[1]}</span><b>${third[2]}</b></a><a data-nav="/staff/health" href="#/staff/health"><span aria-hidden="true">＋</span><b>${tr('health')}</b></a><button type="button" id="app-more-button" aria-expanded="false" aria-controls="mobile-menu"><span aria-hidden="true">•••</span><b>${tr('more')}</b></button></nav>`;
  }
  return `<nav class="app-tabbar" aria-label="${tr('appNavigation')}"><a data-nav="/" href="#/"><span aria-hidden="true">⌂</span><b>${tr('home')}</b></a><a data-nav="/identify" href="#/identify"><span aria-hidden="true">▣</span><b>${tr('identify')}</b></a><a data-nav="/map" href="#/map"><span aria-hidden="true">⌖</span><b>${tr('explore')}</b></a><a data-nav="/insights" href="#/insights"><span aria-hidden="true">▥</span><b>${tr('insights')}</b></a><button type="button" id="app-more-button" aria-expanded="false" aria-controls="mobile-menu"><span aria-hidden="true">•••</span><b>${tr('more')}</b></button></nav>`;
}
function shell(content){
  const pendingId='pending-count-global';
  return `<a class="skip-link" href="#main-content">${getLanguage()==='af'?'Spring na hoofinhoud':'Skip to main content'}</a>
  <header class="site-header"><a class="brand" href="#/" aria-label="${esc(cfg.appName)}"><span class="brand-emblem" aria-hidden="true">🐢</span><span class="brand-copy"><strong>Nautilus Bay</strong><small>${tr('appName')}</small></span></a>
  <nav class="desktop-nav" aria-label="${tr('primaryNavigation')}"><a data-nav="/" href="#/">${tr('home')}</a><a data-nav="/identify" href="#/identify">${tr('identify')}</a><a data-nav="/directory" href="#/directory">${tr('directory')}</a><a data-nav="/map" href="#/map">${tr('explore')}</a><a data-nav="/insights" href="#/insights">${tr('insights')}</a><a data-nav="/about" href="#/about">${tr('about')}</a><a data-nav="/login" href="#/login">${tr('staff')}</a></nav>
  <div class="header-actions"><span class="app-mode-badge" aria-hidden="true">${platform.native?'APP':platform.standalone?'PWA':''}</span><button class="quiet-btn" id="language-btn" aria-label="${tr('changeLanguage')}">${getLanguage()==='en'?'AF':'EN'}</button></div></header>
  <button id="mobile-menu-scrim" class="mobile-menu-scrim" hidden aria-label="${tr('closeMenu')}"></button><nav id="mobile-menu" class="mobile-menu app-sheet" hidden aria-label="${tr('mobileNavigation')}"><div class="sheet-handle" aria-hidden="true"></div><div class="sheet-head"><strong>${tr('more')}</strong><button class="quiet-btn" id="mobile-menu-close" aria-label="${tr('closeMenu')}">×</button></div>${mobileMenuLinks()}<button class="text-button app-install-action" data-install-button hidden>${tr('install')}</button></nav>
  <div id="network-slot"></div><div id="update-slot" class="update-slot" hidden></div>
  <main id="main-content" tabindex="-1">${content}</main>
  <footer class="site-footer"><div><strong>${tr('reserve')}</strong><span>${tr('footerTagline')}</span></div><div class="footer-links"><a href="#/privacy">${tr('privacy')}</a><a href="#/about">${tr('about')}</a><button class="text-button" data-install-button hidden>${tr('install')}</button></div></footer>
  ${appTabbar()}<div class="sync-pill" id="${pendingId}" hidden></div><div class="toast" id="toast" role="status" aria-live="polite"></div><div id="dialog-root"></div>`;
}

function toast(message,type=''){ const e=document.querySelector('#toast'); if(!e)return; e.textContent=message; e.className=`toast show ${type}`; clearTimeout(toast.timer); toast.timer=setTimeout(()=>e.className='toast',3200); }
function modal(html){
  const root=document.querySelector('#dialog-root'); state.modalReturnFocus=document.activeElement;
  root.innerHTML=`<dialog class="modal" aria-modal="true"><div class="modal-inner">${html}</div></dialog>`;
  const d=root.querySelector('dialog');
  const close=()=>{ try{d.close();}catch{} root.innerHTML=''; state.modalReturnFocus?.focus?.(); };
  d.addEventListener('cancel',e=>{e.preventDefault();close();});
  d.addEventListener('click',e=>{if(e.target===d)close();});
  root.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);
  d.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const focusable=[...d.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled&&!x.hidden);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
  d.showModal(); requestAnimationFrame(()=>d.querySelector('input,select,textarea,button')?.focus()); return root;
}
function pageHead(eyebrow,title,text=''){ return `<div class="page-heading"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${text?`<p class="lede">${text}</p>`:''}</div>`; }
function stat(value,label,extra=''){ return `<div class="stat-card"><strong>${esc(value)}</strong><span>${label}</span>${extra?`<small>${extra}</small>`:''}</div>`; }
function animalCard(a){ const common=getLanguage()==='af'?(a.common_name_af||a.common_name_en):(a.common_name_en||a.common_name_af); return `<article class="animal-card"><a href="#/t/${a.public_id}" aria-label="${tr('meet')} ${esc(a.name||a.public_id)}"><div class="animal-visual"><img src="${esc(safeImageUrl(a.profile_photo_url))}" alt="${esc(a.name?tr('profilePhotoOf')+' '+a.name:tr('tortoiseProfilePhoto'))}" loading="lazy"><div class="animal-id">${esc(a.public_id)}</div></div><div class="animal-card-copy"><div class="kicker">${esc(common||tr('tortoiseGeneric'))}</div><h3>${esc(a.name||a.public_id)}</h3><p><em>${esc(a.scientific_name||'')}</em></p><span class="arrow-link">${tr('meet')} ${esc(a.name||a.public_id)} →</span></div></a></article>`; }

async function homeView(){
  const animals=await Repo.publicAnimals(); const map=await Repo.publicMap();
  const month=new Date().getMonth(),year=new Date().getFullYear(); const thisMonth=map.filter(o=>{const d=new Date(o.observed_at);return d.getMonth()===month&&d.getFullYear()===year;}).length;
  let verified='—',health='—'; if(isDemo()){ const all=DemoDB.observations(); verified=all.length?`${Math.round(100*all.filter(o=>o.verification_status==='verified').length/all.length)}%`:'—'; health=DemoDB.all('health_cases').filter(c=>c.status!=='closed').length; }
  return `<section class="hero"><div class="hero-pattern" aria-hidden="true"></div><div class="hero-content"><div class="eyebrow light">${tr('heroEyebrow')}</div><h1>${tr('heroTitle')}</h1><p>${tr('heroText')}</p><div class="hero-actions"><a class="btn primary light" href="#/scan">▣ ${tr('scanQr')}</a><a class="btn secondary light" href="#/identify">${tr('enterId')}</a></div><div class="safety-note"><span aria-hidden="true">◌</span><span>${tr('observeSafely')}</span></div></div><div class="hero-orbit" aria-hidden="true"><div class="orbit-shell">🐢</div></div></section>
  <section class="section overlap"><div class="stats-grid">${stat(animals.length,tr('registeredAnimals'))}${stat(thisMonth,tr('sightingsMonth'))}${stat(verified,tr('verifiedRate'))}${stat(health,tr('healthAlerts'))}</div></section>
  <section class="section split-intro"><div>${pageHead(tr('communityScience'),tr('recentTortoises'),'')}</div><div class="intro-actions"><a class="btn secondary" href="#/untagged">${tr('reportUntagged')}</a><a class="text-link" href="#/directory">${tr('exploreTortoises')} →</a></div></section>
  <section class="section cards-grid">${animals.slice(0,6).map(animalCard).join('')||`<div class="empty">${tr('noRecords')}</div>`}</section>
  <section class="section impact-panel"><div><div class="eyebrow">${tr('conservationByDesign')}</div><h2>${tr('aboutTitle')}</h2><p>${tr('aboutText')}</p></div><div class="impact-list"><div><strong>01</strong><span>${tr('aboutScience')}</span></div><div><strong>02</strong><span>${tr('aboutOffline')}</span></div><div><strong>03</strong><span>${tr('aboutFuture')}</span></div></div></section>`;
}

function identifyView(){ return `<section class="section narrow">${pageHead(tr('fieldIdentification'),tr('identifyTitle'),tr('identifyHelp'))}<div class="form-card"><form id="identify-form"><label class="field"><span>${tr('tortoiseId')}</span><input id="tortoise-id" name="id" maxlength="24" autocomplete="off" autocapitalize="characters" placeholder="${tr('idPlaceholder')}" required /></label><div id="identify-error" class="form-error" role="alert"></div><button class="btn primary wide" type="submit">${tr('find')}</button><a class="btn secondary wide" href="#/scan">▣ ${tr('scanQr')}</a></form></div></section>`; }

function scanView(){ return `<section class="section narrow">${pageHead(tr('qrIdentification'),tr('qrTitle'),tr('qrExplain'))}<div class="scanner-card"><div id="scanner-stage" class="scanner-stage"><div class="scanner-placeholder"><span>▣</span><strong>${tr('qrTitle')}</strong></div></div><p id="scan-status" class="hint" role="status"></p><div class="button-row"><button id="scan-start" class="btn primary">${tr('openCamera')}</button><a class="btn secondary" href="#/identify">${tr('enterId')}</a></div></div></section>`; }

async function profileView(publicId){
  const a=await Repo.publicAnimal(publicId); if(!a)return notFoundView(); const hist=await Repo.publicHistory(publicId);
  const taxName=getLanguage()==='af'?(a.common_name_af||a.common_name_en):(a.common_name_en||a.common_name_af);
  return `<section class="profile-hero section"><div class="profile-visual"><img class="profile-photo" src="${esc(safeImageUrl(a.profile_photo_url))}" alt="${esc(a.name?tr('profilePhotoOf')+' '+a.name:tr('tortoiseProfilePhoto'))}"><span class="id-chip">${esc(a.public_id)}</span></div><div class="profile-copy"><div class="eyebrow">${tr('meet')}</div><h1>${esc(a.name||a.public_id)}</h1><p class="scientific"><strong>${esc(taxName||'Tortoise')}</strong> · <em>${esc(a.scientific_name||'')}</em></p><div class="profile-actions"><a class="btn primary" href="#/sighting/${a.public_id}">${tr('seenThis')}</a><a class="btn secondary" href="#/t/${a.public_id}?tab=movement">${tr('movement')}</a><button class="btn secondary share-profile" type="button" data-share-profile="${esc(a.public_id)}">↗ ${tr('share')}</button></div></div></section>
  <section class="section profile-grid"><article class="detail-card"><h2>${tr('animalTimeline')}</h2><dl class="details"><div><dt>${tr('species')}</dt><dd>${esc(taxName||'—')}</dd></div><div><dt>${tr('scientificName')}</dt><dd><em>${esc(a.scientific_name||'—')}</em></dd></div><div><dt>${tr('sex')}</dt><dd>${esc(human(a.sex)||'—')}</dd></div><div><dt>${tr('lifeStage')}</dt><dd>${esc(human(a.life_stage)||'—')}</dd></div><div><dt>${tr('approxAge')}</dt><dd>${a.estimated_age_years?`${esc(a.estimated_age_years)} ${tr('years')}`:'—'}</dd></div><div><dt>${tr('lastSeen')}</dt><dd>${a.last_observed_at?`${fmtDate(a.last_observed_at)} · ${daysAgo(a.last_observed_at)}`:'—'}</dd></div>${a.conservation_status?`<div><dt>${tr('conservationStatus')}</dt><dd>${esc(a.conservation_status)}</dd></div>`:''}</dl><div class="feature-box"><strong>${tr('distinguishing')}</strong><p>${esc(a.identifying_features||'—')}</p></div></article>
  <article class="detail-card map-card"><div class="card-head"><div><span class="eyebrow">${tr('movement')}</span><h2>${hist.length} ${tr('observationsLabel')}</h2></div></div><p class="security-note">${tr('publicLocationNotice')}</p><div id="profile-map" class="map-frame" aria-label="Generalised movement map"><div class="map-loader">${tr('loadingMap')}</div></div><p class="map-disclaimer">${tr('inferredLine')}</p></article></section>
  ${accessibleObservationList(hist,a.name||a.public_id)}`;
}

function accessibleObservationList(rows,name=''){ return `<section class="section"><details class="accessible-list"><summary>${tr('sightingList')} (${rows.length})</summary><ol>${rows.slice().reverse().map(o=>`<li><strong>${fmt(o.observed_at)}</strong><span>${esc(human(o.behaviour||'observed'))} · ${esc(human(o.condition||'unknown'))}</span><span>${tr('publicGeneralisedLocation')}</span></li>`).join('')||`<li>${tr('noRecords')}</li>`}</ol></details></section>`; }

function sightingView(publicId=null,untagged=false){
  const source=untagged?'untagged':(sessionStorage.getItem('nautilus-identification-source')||'manual');
  return `<section class="section narrow sighting-flow">${pageHead(untagged?'Unassigned observation':publicId||'',untagged?tr('untaggedTitle'):tr('sightingTitle'),untagged?tr('untaggedExplain'):'')}
  <div class="progress" aria-label="Sighting progress"><span class="active" data-step="1" aria-current="step">1 ${tr('location')}</span><span data-step="2">2 ${tr('photo')}</span><span data-step="3">3 ${tr('condition')}</span><span data-step="4">4 ${tr('review')}</span></div>
  <form id="sighting-form" class="flow-card" data-public-id="${esc(publicId||'')}" data-untagged="${untagged}" data-source="${esc(source)}" data-client-id="${uuid()}">
    <section class="flow-step" data-flow-step="1"><div class="step-number">1</div><div class="step-body"><h2>${tr('locationPreTitle')}</h2><p>${tr('locationPreText')}</p><div class="location-status" id="gps-status"><span class="status-dot neutral"></span><strong>${tr('gpsUnavailable')}</strong></div><button id="gps-button" class="btn primary" type="button">◎ ${tr('allowLocation')}</button><div class="flow-navigation"><button type="button" class="btn primary" data-next-step="2">${tr('next')}</button></div><input type="hidden" id="lat"><input type="hidden" id="lng"><input type="hidden" id="accuracy"></div></section>
    <section class="flow-step" data-flow-step="2" hidden><div class="step-number">2</div><div class="step-body"><h2>${tr('photoTitle')}</h2><p>${tr('photoProtocol')}</p><div class="photo-guidance"><span>◉ Top</span><span>◧ Side</span><span>◌ Full shell</span></div><label class="upload-button"><span>📷 ${tr('addPhotos')}</span><input id="photos" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple /></label><small>${tr('photoRequired')} · ${tr('photoLimit')} · ${tr('avoidPeople')}</small><div id="photo-previews" class="photo-previews"></div><div class="flow-navigation"><button type="button" class="btn secondary" data-prev-step="1">${tr('back')}</button><button type="button" class="btn primary" data-next-step="3">${tr('next')}</button></div></div></section>
    <section class="flow-step" data-flow-step="3" hidden><div class="step-number">3</div><div class="step-body"><h2>${tr('condition')}</h2>${untagged?`<label class="field"><span>${tr('possibleSpecies')} (${tr('optional')})</span><select id="possible-species"><option value="">${tr('dontKnow')}</option><option>Leopard tortoise</option><option>Angulate tortoise</option><option>Padloper</option><option>${tr('other')}</option></select></label>`:''}
      <fieldset><legend>${tr('identificationConfidence')}</legend><div class="choice-row" data-choice="identification_confidence">${choice('certain',tr('certain'),true)}${choice('probable',tr('probable'))}${choice('uncertain',tr('uncertain'))}</div></fieldset>
      <fieldset><legend>${tr('behaviour')}</legend><div class="choice-grid" data-choice="behaviour">${choice('walking',tr('walking'))}${choice('feeding',tr('feeding'))}${choice('resting',tr('resting'))}${choice('mating',tr('mating'))}${choice('crossing',tr('crossing'))}${choice('unknown',tr('unknown'),true)}${choice('other',tr('other'))}</div></fieldset>
      <fieldset><legend>${tr('appearance')}</legend><div class="choice-grid" data-choice="condition">${choice('healthy',tr('healthy'),true)}${choice('possible_injury',tr('possibleInjury'))}${choice('shell_damage',tr('shellDamage'))}${choice('unusual',tr('unusual'))}${choice('dead',tr('dead'))}${choice('unsure',tr('unsure'))}</div></fieldset>
      <label class="field"><span>${tr('notes')}</span><textarea id="notes" rows="3" maxlength="500" placeholder="${tr('notesPlaceholder')}"></textarea></label><div id="condition-alert" class="condition-alert" hidden></div><div class="flow-navigation"><button type="button" class="btn secondary" data-prev-step="2">${tr('back')}</button><button type="button" class="btn primary" data-next-step="4">${tr('review')}</button></div></div></section>
    <section class="flow-step final-step" data-flow-step="4" hidden><div class="step-number">4</div><div class="step-body"><h2>${tr('review')}</h2><div id="quality-preview" class="quality-preview"></div><div class="safety-note dark"><span>◌</span><span>${tr('observeSafely')}</span></div>${cfg.turnstileSiteKey?'<div id="turnstile-widget" class="turnstile-slot"></div>':''}<div class="flow-navigation"><button type="button" class="btn secondary" data-prev-step="3">${tr('back')}</button></div><button id="submit-sighting" class="btn primary wide" type="submit">${tr('submit')}</button><div id="submit-error" class="form-error" role="alert"></div></div></section>
  </form></section>`;
}
function choice(value,label,selected=false){ return `<button type="button" class="choice ${selected?'selected':''}" data-value="${value}" aria-pressed="${selected}">${label}</button>`; }

function confirmationView(){ const o=state.lastSubmission||JSON.parse(sessionStorage.getItem('nautilus-last-submission')||'null'); if(!o)return `<section class="section narrow">${pageHead('',tr('thankYou'))}<a class="btn primary" href="#/">${tr('returnHome')}</a></section>`; return `<section class="section narrow"><div class="confirmation"><div class="success-ring">✓</div><div class="eyebrow">${tr('contribution')}</div><h1>${tr('thankYou')}</h1><p>${o.queued?tr('offlineSaved'):tr('submitted')}</p><div class="confirmation-meta"><span>${esc(o.public_id||'UNTAGGED')}</span><span>${fmt(o.observed_at)}</span><span>${tr('accuracy')} ±${Math.round(o.accuracy_m)} m</span><span>${tr('recordQuality')}: ${tr('recordQuality'+qualityBand(o.quality_score).replace(/^./,c=>c.toUpperCase()))}</span></div>${o.public_id?`<a class="btn primary" href="#/t/${o.public_id}">${tr('viewJourney')}</a>`:`<a class="btn primary" href="#/">${tr('returnHome')}</a>`}</div></section>`; }

async function mapView(){ const rows=await Repo.publicMap(); const animals=await Repo.publicAnimals(); const species=[...new Set(animals.map(a=>getLanguage()==='af'?(a.common_name_af||a.common_name_en):(a.common_name_en||a.common_name_af)).filter(Boolean))]; return `<section class="section">${pageHead(tr('publicConservationMap'),tr('mapTitle'),tr('mapHelp'))}<div class="analysis-toolbar public-map-tools"><label>${tr('filterAnimal')}<select id="map-filter"><option value="all">${tr('allTortoises')}</option>${animals.map(a=>`<option value="${a.public_id}">${esc(a.public_id)} — ${esc(a.name||'')}</option>`).join('')}</select></label><label>${tr('theme')}<select id="map-theme"><option value="species">${tr('themeSpecies')}</option><option value="recency">${tr('themeRecency')}</option><option value="density">${tr('themeDensity')}</option><option value="points">${tr('themePoints')}</option></select></label><label>${tr('dateFrom')}<input id="map-from" type="date"></label><label>${tr('dateTo')}<input id="map-to" type="date"></label><label id="public-density-size" hidden>${tr('cellSize')}<select id="map-cell-size"><option value="250">250 m</option><option value="500" selected>500 m</option><option value="1000">1 km</option></select></label><button type="button" class="btn secondary small" id="map-clear">${tr('clearFilters')}</button></div><div class="map-summary" id="public-map-summary"></div><div id="main-map" class="map-frame large"><div class="map-loader">${tr('loadingMap')}</div></div><p class="map-disclaimer">${tr('publicLocationNotice')}</p><div id="public-map-list">${accessibleObservationList(rows)}</div></section>`; }

async function publicInsightsView(){
  const [rows,animals]=await Promise.all([Repo.publicMap(),Repo.publicAnimals()]); const byId=new Map(animals.map(a=>[a.public_id,a])); const enriched=rows.map(r=>{const a=byId.get(r.public_id)||{};return {...r,animal_id:a.id||r.animal_id,species_name:getLanguage()==='af'?(a.common_name_af||a.common_name_en):(a.common_name_en||a.common_name_af)};});
  const months=monthlyCounts(enriched,locale()),species=categoryCounts(enriched,'species_name'),beh=categoryCounts(enriched,'behaviour'),seen=new Set(enriched.map(r=>r.public_id).filter(Boolean)).size;
  return `<section class="section">${pageHead(tr('communityScience'),tr('publicInsights'),tr('publicInsightHelp'))}<div class="notice info">${tr('publicAggregateNotice')}</div><div class="stats-grid">${stat(enriched.length,tr('filteredObservations'))}${stat(seen,tr('uniqueAnimals'))}${stat(species.length,tr('species'))}${stat(months.length,tr('timeRange'))}</div><div class="viz-grid">${lineChart(tr('sightingsTrend'),months,{description:tr('publicAggregateNotice')})}${barChart(tr('speciesSightings'),species,{description:tr('publicAggregateNotice')})}${barChart(tr('behaviourMix'),beh,{description:tr('publicAggregateNotice')})}${matrixChart(tr('dataFingerprint'),observationMatrix(enriched,locale()),tr('publicAggregateNotice'))}</div></section>`;
}


async function directoryView(){ const animals=await Repo.publicAnimals(); const taxa=[...new Set(animals.map(a=>getLanguage()==='af'?(a.common_name_af||a.common_name_en):(a.common_name_en||a.common_name_af)).filter(Boolean))].sort(); return `<section class="section">${pageHead(tr('communityScience'),tr('directoryTitle'),tr('directoryHelp'))}<div class="directory-tools"><label class="field"><span>${tr('searchAnimals')}</span><input id="directory-search" type="search" autocomplete="off" placeholder="${tr('searchAnimalsPlaceholder')}"></label><label class="field"><span>${tr('species')}</span><select id="directory-species"><option value="">${tr('allSpecies')}</option>${taxa.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}</select></label></div><div id="directory-count" class="directory-count"></div><div id="directory-grid" class="cards-grid">${animals.map(animalCard).join('')}</div></section>`; }
function bindDirectory(){const q=document.querySelector('#directory-search'),species=document.querySelector('#directory-species'),grid=document.querySelector('#directory-grid'),count=document.querySelector('#directory-count');if(!q||!grid)return;const cards=[...grid.children];const apply=()=>{let n=0;for(const card of cards){const text=card.textContent.toLowerCase(),s=species.value.toLowerCase();const show=(!q.value||text.includes(q.value.toLowerCase()))&&(!s||text.includes(s));card.hidden=!show;if(show)n++;}count.textContent=`${n} ${tr('animalsFound')}`;};q.oninput=apply;species.onchange=apply;apply();}

function aboutView(){ return `<section class="section narrow-wide">${pageHead(tr('platformName'),tr('aboutTitle'),tr('aboutText'))}<div class="principles-grid"><article><span>01</span><h2>${tr('aboutScience')}</h2><p>${tr('aboutScienceText')}</p></article><article><span>02</span><h2>${tr('aboutOffline')}</h2><p>${tr('aboutOfflineText')}</p></article><article><span>03</span><h2>${tr('aboutFuture')}</h2><p>${tr('aboutFutureText')}</p></article></div><div class="ethics-panel"><h2>${tr('citizenScienceNoDisturbance')}</h2><p>${tr('observeSafely')}</p></div></section>`; }
function privacyView(){ return `<section class="section narrow">${pageHead(tr('privacyByDesign'),tr('privacyTitle'),tr('privacyText'))}<div class="prose-card"><h2>${tr('publicSightingsHeading')}</h2><p>${tr('publicSightingsPrivacy')}</p><h2>${tr('animalLocationSecurity')}</h2><p>${tr('publicLocationNotice')}</p><h2>${tr('photographsHeading')}</h2><p>${tr('avoidPeople')}</p><h2>${tr('productionGovernance')}</h2><p>${tr('dataRights')}</p></div></section>`; }

function loginView(){ if(isDemo()) return `<section class="section narrow">${pageHead('Restricted area',tr('staffAccess'),tr('demoText'))}<div class="role-grid"><button class="role-card" data-demo-role="admin"><span>◆</span><strong>${tr('admin')}</strong><small>MFA-enforced production role</small></button><button class="role-card" data-demo-role="ranger"><span>⌖</span><strong>${tr('ranger')}</strong><small>Field verification and health alerts</small></button><button class="role-card" data-demo-role="researcher"><span>⌁</span><strong>${tr('researcher')}</strong><small>Research, export and deployments</small></button><button class="role-card" data-demo-role="veterinarian"><span>＋</span><strong>${tr('veterinarian')}</strong><small>Health case management</small></button></div><p class="demo-warning">${tr('demoMode')}: no production credentials are used.</p></section>`;
  return `<section class="section narrow">${pageHead('Restricted area',tr('staffAccess'),'')}<div class="form-card"><form id="login-form"><label class="field"><span>${tr('email')}</span><input type="email" id="login-email" autocomplete="username" required></label><label class="field"><span>${tr('password')}</span><input type="password" id="login-password" autocomplete="current-password" required></label><button class="btn primary wide" type="submit">${tr('signIn')}</button><div id="login-error" class="form-error"></div></form></div></section>`; }
function mfaView(factorId,challengeId){ return `<section class="section narrow">${pageHead('Multi-factor authentication','Administrator MFA required','Enter the current code from your enrolled authenticator.')}<div class="form-card"><form id="mfa-form" data-factor="${esc(factorId)}" data-challenge="${esc(challengeId)}"><label class="field"><span>${tr('mfaCode')}</span><input id="mfa-code" inputmode="numeric" pattern="[0-9]{6,8}" autocomplete="one-time-code" required></label><button class="btn primary wide">${tr('verifyMfa')}</button><div id="mfa-error" class="form-error"></div></form></div></section>`; }

function staffNav(section){ const role=state.role; const links=[['dashboard',tr('dashboard')],['insights',tr('insights')],['animals',tr('animals')],['observations',tr('observations')],['health',tr('health')]]; if(['ranger','researcher','admin'].includes(role))links.push(['spatial',tr('mapLab')]); if(['researcher','admin'].includes(role))links.push(['research',tr('research')],['devices',tr('devices')],['export',tr('exportData')]); if(role==='admin')links.push(['qr',tr('qrCodes')],['audit',tr('audit')],['settings',tr('settings')]); return `<aside class="staff-nav"><div class="staff-identity"><span>${roleIcon(role)}</span><strong>${esc(state.staffName||human(role))}</strong><small>${human(role)}</small></div><nav>${links.map(([id,label])=>`<a class="${section===id?'active':''}" href="#/staff/${id}">${label}</a>`).join('')}<a href="#/logout">${tr('logout')}</a></nav></aside>`; }
function roleIcon(r){ return ({admin:'◆',ranger:'⌖',researcher:'⌁',veterinarian:'＋'})[r]||'•'; }
function roleAllowed(section){ const r=state.role; if(!r)return false; if(['dashboard','insights','animals','observations','health'].includes(section))return true; if(section==='spatial')return ['ranger','researcher','admin'].includes(r); if(['research','devices','export'].includes(section))return ['researcher','admin'].includes(r); return r==='admin'; }

async function staffView(section='dashboard'){
  if(!state.role)return loginView(); if(!roleAllowed(section))return `<section class="section narrow"><div class="notice danger">Access denied for this role.</div></section>`;
  const data=await Repo.staffSnapshot(); let body='';
  if(section==='dashboard')body=staffDashboard(data); if(section==='insights')body=staffInsights(data); if(section==='spatial')body=staffSpatial(data); if(section==='animals')body=staffAnimals(data); if(section==='observations')body=staffObservations(data); if(section==='health')body=staffHealth(data); if(section==='research')body=staffResearch(data); if(section==='devices')body=staffDevices(data); if(section==='export')body=staffExport(data); if(section==='qr')body=staffQr(data); if(section==='audit')body=staffAudit(data); if(section==='settings')body=staffSettings(data);
  return `<div class="staff-shell">${staffNav(section)}<section class="staff-content">${body}</section></div>`;
}

function enrichStaffRows(d){ const animals=new Map(d.animals.map(a=>[a.id,a])); const taxa=new Map(d.taxa.map(t=>[t.id,t])); return d.observations.map(o=>{const a=animals.get(o.animal_id)||d.animals.find(x=>x.public_id===o.public_id)||{},t=taxa.get(a.taxon_id)||{};return {...o,public_id:o.public_id||a.public_id,name:a.name||'',species_name:getLanguage()==='af'?(t.common_name_af||t.common_name_en):(t.common_name_en||t.common_name_af),scientific_name:t.scientific_name||'',accuracy_m:o.accuracy_m??o.gps_accuracy_m};}); }
function staffInsights(d){
  const rows=enrichStaffRows(d),months=monthlyCounts(rows,locale()),species=categoryCounts(rows,'species_name'),beh=categoryCounts(rows,'behaviour'),conditions=categoryCounts(rows,'condition'),quality=qualityBands(rows),hours=hourBands(rows),seen=new Set(rows.map(r=>r.public_id).filter(Boolean)).size,med=median(rows.map(r=>r.accuracy_m)),verified=rows.length?Math.round(100*rows.filter(r=>r.verification_status==='verified').length/rows.length):0,last=lastSeenRows(d.animals,rows).slice(0,8),movement=movementMetrics(d.animals,rows).filter(x=>x.sightings>1).slice(0,10);
  return `${pageHead(tr('dataInsights'),tr('insights'),tr('insightHelp'))}<div class="stats-grid staff-stats">${stat(rows.length,tr('filteredObservations'))}${stat(seen,tr('uniqueAnimals'))}${stat(`${verified}%`,tr('verifiedRate'))}${stat(med==null?'—':`${Math.round(med)} m`,tr('medianGpsAccuracy'))}</div><div class="viz-grid">${lineChart(tr('sightingsTrend'),months)}${barChart(tr('speciesSightings'),species)}${barChart(tr('behaviourMix'),beh)}${barChart(tr('conditionMix'),conditions)}${barChart(tr('qualityDistribution'),quality)}${barChart(tr('activityTime'),hours)}${matrixChart(tr('dataFingerprint'),observationMatrix(rows,locale()),tr('analyticalCaution'))}</div><div class="staff-panels analytics-panels"><article class="panel"><h2>${tr('lastSeenWatchlist')}</h2><div class="watchlist">${last.map(x=>`<div><strong>${esc(x.public_id)} · ${esc(x.name)}</strong><span>${x.last_seen?fmtDate(x.last_seen):tr('noRecords')}</span><b>${x.days==null?'—':x.days+' d'}</b></div>`).join('')}</div></article><article class="panel"><h2>${tr('movementSummary')}</h2><p class="map-disclaimer">${tr('analyticalCaution')}</p><div class="table-wrap"><table><thead><tr><th>Animal</th><th>${tr('observationsLabel')}</th><th>${tr('observedDisplacement')}</th><th>${tr('maxDisplacement')}</th></tr></thead><tbody>${movement.map(m=>`<tr><td>${esc(m.public_id)} · ${esc(m.name)}</td><td>${m.sightings}</td><td>${m.connection_sum_m>=1000?(m.connection_sum_m/1000).toFixed(2)+' km':m.connection_sum_m+' m'}</td><td>${m.max_displacement_m>=1000?(m.max_displacement_m/1000).toFixed(2)+' km':m.max_displacement_m+' m'}</td></tr>`).join('')}</tbody></table></div></article></div>`;
}
function staffSpatial(d){
  const animals=d.animals.filter(a=>a.status==='active'),species=[...new Set(d.taxa.map(t=>getLanguage()==='af'?(t.common_name_af||t.common_name_en):(t.common_name_en||t.common_name_af)).filter(Boolean))].sort();
  return `${pageHead(tr('spatialAnalysis'),tr('spatialLab'),tr('spatialHelp'))}<div class="analysis-toolbar spatial-toolbar"><label>${tr('filterAnimal')}<select id="spatial-animal"><option value="all">${tr('allTortoises')}</option>${animals.map(a=>`<option value="${esc(a.public_id)}">${esc(a.public_id)} — ${esc(a.name||'')}</option>`).join('')}</select></label><label>${tr('species')}<select id="spatial-species"><option value="">${tr('allSpecies')}</option>${species.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>${tr('condition')}<select id="spatial-condition"><option value="">${tr('allConditions')}</option>${['healthy','possible_injury','shell_damage','unusual','dead','unsure'].map(x=>`<option value="${x}">${human(x)}</option>`).join('')}</select></label><label>${tr('verification')}<select id="spatial-verification"><option value="">${tr('allStatuses')}</option>${['verified','pending','questionable','rejected'].map(x=>`<option value="${x}">${human(x)}</option>`).join('')}</select></label><label>${tr('dateFrom')}<input id="spatial-from" type="date"></label><label>${tr('dateTo')}<input id="spatial-to" type="date"></label><label>${tr('theme')}<select id="spatial-theme"><option value="species">${tr('themeSpecies')}</option><option value="condition">${tr('themeCondition')}</option><option value="quality">${tr('themeQuality')}</option><option value="verification">${tr('themeVerification')}</option><option value="recency">${tr('themeRecency')}</option><option value="density">${tr('themeDensity')}</option><option value="points">${tr('themePoints')}</option></select></label><label id="spatial-density-wrap" hidden>${tr('cellSize')}<select id="spatial-cell"><option value="100">100 m</option><option value="250" selected>250 m</option><option value="500">500 m</option><option value="1000">1 km</option></select></label><label class="check-field"><input id="spatial-accuracy" type="checkbox"> ${tr('showAccuracyCircles')}</label><button id="spatial-clear" class="btn secondary small" type="button">${tr('clearFilters')}</button></div><div id="spatial-summary" class="map-summary"></div><div id="staff-map" class="map-frame extra-large"><div class="map-loader">${tr('loadingMap')}</div></div><p class="map-disclaimer">${tr('mapMeasureHelp')} ${tr('analyticalCaution')}</p><div class="export-inline"><strong>${tr('exportFiltered')}</strong><button data-spatial-export="kml" class="btn secondary small">KML</button><button data-spatial-export="kml-connections" class="btn secondary small">KML + connections</button><button data-spatial-export="geojson" class="btn secondary small">GeoJSON</button><button data-spatial-export="csv" class="btn secondary small">CSV</button><small>${tr('exactStaffCoordinates')}</small></div><div id="spatial-table" class="table-card spatial-table"></div>`;
}
function staffDashboard(d){ const active=d.animals.filter(a=>a.status==='active').length,unreviewed=d.observations.filter(o=>o.verification_status==='pending').length,low=d.observations.filter(o=>(o.quality_score||0)<70).length,health=d.health_cases.filter(c=>c.status!=='closed').length; return `${pageHead('Operational overview',tr('dashboard'),'Scientific and operational health at a glance.')}<div class="stats-grid staff-stats">${stat(active,tr('totalAnimals'))}${stat(unreviewed,tr('unreviewed'))}${stat(low,tr('qualityLow'))}${stat(health,tr('healthAlerts'))}</div><div class="staff-panels"><article class="panel"><h2>${tr('recentActivity')}</h2>${d.observations.slice().sort((a,b)=>new Date(b.observed_at)-new Date(a.observed_at)).slice(0,6).map(o=>`<div class="activity"><span class="quality-dot ${qualityBand(o.quality_score||0)}"></span><div><strong>${esc(o.public_id||'UNTAGGED')} · ${human(o.condition)}</strong><small>${fmt(o.observed_at)} · Q${o.quality_score||'—'}</small></div></div>`).join('')}</article><article class="panel"><h2>${tr('healthAlerts')}</h2>${d.health_cases.filter(c=>c.status!=='closed').map(c=>`<div class="case-row"><span class="severity ${c.severity}">${human(c.severity)}</span><div><strong>${esc(c.summary)}</strong><small>${human(c.status)} · ${c.follow_up_date?fmtDate(c.follow_up_date):'No follow-up date'}</small></div></div>`).join('')||`<div class="empty">${tr('noRecords')}</div>`}</article></div><div class="governance-strip"><span>✓ ${tr('immutable')}</span><span>⚑ Public coordinates generalised</span><span>⌁ Offline queue protected</span></div>`; }
function staffAnimals(d){ return `${pageHead('Master animal registry',tr('animals'),'Permanent animal identity separated from sightings, tags and deployments.')}<div class="staff-toolbar"><input id="animal-search" class="search-input" placeholder="Search ID, name or species"><button id="add-animal" class="btn primary">＋ ${tr('addAnimal')}</button></div><div class="table-card"><table><thead><tr><th>${tr('publicId')}</th><th>${tr('name')}</th><th>${tr('species')}</th><th>${tr('sex')}</th><th>${tr('lastSeen')}</th><th>${tr('status')}</th><th></th></tr></thead><tbody id="animal-table">${animalRows(d)}</tbody></table></div>`; }
function animalRows(d,term=''){ return d.animals.filter(a=>{const tax=d.taxa.find(t=>t.id===a.taxon_id);return`${a.public_id} ${a.name} ${tax?.common_name_en||''}`.toLowerCase().includes(term.toLowerCase());}).map(a=>{const tax=d.taxa.find(t=>t.id===a.taxon_id);const latest=d.observations.filter(o=>o.animal_id===a.id).sort((x,y)=>new Date(y.observed_at)-new Date(x.observed_at))[0];return`<tr><td><a href="#/t/${a.public_id}"><strong>${esc(a.public_id)}</strong></a></td><td>${esc(a.name||'—')}</td><td>${esc(tax?.common_name_en||'—')}<small><em>${esc(tax?.scientific_name||'')}</em></small></td><td>${human(a.sex)}</td><td>${latest?fmtDate(latest.observed_at):'—'}</td><td><span class="status-chip ${a.status}">${human(a.status)}</span></td><td><button class="table-action" data-edit-animal="${a.id}">${tr('editAnimal')}</button></td></tr>`;}).join(''); }
function staffObservations(d){ return `${pageHead('Append-first scientific record',tr('observationRecord'),tr('qualityExplain'))}<div class="notice info">${tr('immutable')}</div><div class="table-card"><table><thead><tr><th>Date</th><th>Animal</th><th>GPS</th><th>${tr('quality')}</th><th>${tr('condition')}</th><th>${tr('verification')}</th><th></th></tr></thead><tbody>${d.observations.slice().sort((a,b)=>new Date(b.observed_at)-new Date(a.observed_at)).map(o=>`<tr><td>${fmt(o.observed_at)}<small>${esc(human(o.identification_method))}</small></td><td>${esc(o.public_id||'UNTAGGED')}</td><td>±${Math.round(o.accuracy_m||0)} m</td><td><span class="score ${qualityBand(o.quality_score||0)}">${o.quality_score||qualityScore(o)}</span></td><td>${human(o.condition)}</td><td><span class="status-chip ${o.verification_status}">${human(o.verification_status)}</span></td><td><div class="mini-actions"><button data-review="${o.id}" data-status="verified">${tr('verify')}</button><button data-review="${o.id}" data-status="questionable">${tr('flag')}</button><button data-correct="${o.id}">${tr('correct')}</button></div></td></tr>`).join('')}</tbody></table></div>`; }
function staffHealth(d){ return `${pageHead('Wildlife health workflow',tr('healthCases'),'Potential injury observations can become assigned cases with follow-up and outcome records.')}<div class="staff-toolbar"><button id="new-health-case" class="btn primary">＋ ${tr('newHealthCase')}</button></div><div class="case-grid">${d.health_cases.map(c=>{const a=d.animals.find(x=>x.id===c.animal_id);return`<article class="health-card"><div class="health-head"><span class="severity ${c.severity}">${human(c.severity)}</span><span class="status-chip ${c.status}">${human(c.status)}</span></div><h3>${esc(a?.public_id||'Unassigned')} · ${esc(a?.name||'')}</h3><p>${esc(c.summary)}</p><dl><div><dt>${tr('assignedTo')}</dt><dd>${esc(c.assigned_team||c.assigned_to||'—')}</dd></div><div><dt>${tr('followUp')}</dt><dd>${c.follow_up_date?fmtDate(c.follow_up_date):'—'}</dd></div><div><dt>${tr('outcome')}</dt><dd>${esc(c.outcome||'—')}</dd></div></dl><div class="button-row"><button class="btn secondary small" data-health-update="${c.id}">Update case</button><button class="btn secondary small" data-health-event="${c.id}">Clinical event</button></div></article>`;}).join('')||`<div class="empty">${tr('noRecords')}</div>`}</div>`; }
function staffResearch(d){ return `${pageHead('Research-grade provenance',tr('researchTools'),'Measurements retain method, units, confidence, time and recorder.')}<div class="staff-toolbar"><button id="add-measurement" class="btn primary">＋ ${tr('addMeasurement')}</button></div><div class="table-card"><table><thead><tr><th>Animal</th><th>${tr('measurementType')}</th><th>${tr('value')}</th><th>${tr('method')}</th><th>${tr('confidence')}</th><th>${tr('recordedBy')}</th><th>Date</th></tr></thead><tbody>${d.measurements.map(m=>{const a=d.animals.find(x=>x.id===m.animal_id);return`<tr><td>${esc(a?.public_id||'—')}</td><td>${human(m.measurement_type)}</td><td>${esc(m.value)} ${esc(m.unit)}</td><td>${esc(m.method||'—')}</td><td>${human(m.confidence||'—')}</td><td>${esc(m.recorded_by||'—')}</td><td>${fmt(m.measured_at)}</td></tr>`;}).join('')}</tbody></table></div><div class="research-note"><h2>Photo-identification readiness</h2><p>Future computer-vision matching should propose candidates only. Animal identity merges must remain a human-reviewed scientific decision.</p></div>`; }
function staffDevices(d){ return `${pageHead('Animal → device → deployment → event',tr('deploymentTitle'),'Devices can move between animals; the deployment preserves when and how a device was associated with an individual.')}<div class="deployment-diagram"><span>ANIMAL</span><i>→</i><span>DEPLOYMENT</span><i>→</i><span>DEVICE / TAG</span><i>→</i><span>TELEMETRY EVENT</span></div><div class="table-card"><table><thead><tr><th>Animal</th><th>${tr('deviceId')}</th><th>${tr('technology')}</th><th>${tr('installed')}</th><th>${tr('removed')}</th><th>${tr('status')}</th></tr></thead><tbody>${d.deployments.map(dep=>{const a=d.animals.find(x=>x.id===dep.animal_id),dev=d.devices.find(x=>x.id===dep.device_id);return`<tr><td>${esc(a?.public_id||'—')}</td><td>${esc(dev?.external_device_id||'—')}</td><td>${esc(dev?.technology||'—')}</td><td>${fmt(dep.deployed_at)}</td><td>${dep.removed_at?fmt(dep.removed_at):'—'}</td><td>${human(dep.status)}</td></tr>`;}).join('')}</tbody></table></div><div class="notice info">Physical tag/device selection and attachment method remain subject to wildlife/veterinary approval before operational deployment.</div>`; }
function staffExport(){ return `${pageHead('FAIR-ready data',tr('exportTitle'),tr('exportHelp'))}<div class="export-grid"><button class="export-card" data-export="registry"><span>CSV</span><strong>${tr('csv')}</strong><small>Animal master register</small></button><button class="export-card" data-export="observations-csv"><span>CSV</span><strong>Observation CSV</strong><small>Exact authorised observation table</small></button><button class="export-card" data-export="geojson"><span>{ }</span><strong>${tr('geojson')}</strong><small>Exact staff-authorised spatial observations</small></button><button class="export-card" data-export="kml"><span>◉</span><strong>${tr('kml')}</strong><small>OGC KML point observations for Earth/GIS tools</small></button><button class="export-card" data-export="movebank"><span>⌁</span><strong>${tr('movebank')}</strong><small>Event-oriented movement export</small></button></div><div class="notice info">${tr('mapExportHelp')}</div>`; }
function staffQr(d){ const base=cfg.siteUrl.replace(/\/$/,''); return `${pageHead('Self-hosted QR identification',tr('qrCodes'),tr('qrHelp'))}<div class="qr-grid">${d.animals.filter(a=>a.status==='active').map(a=>`<article class="qr-card"><div class="qr-placeholder" id="qr-${a.public_id}"><span>▣</span></div><h3>${esc(a.public_id)} · ${esc(a.name||'')}</h3><code>${esc(base)}/#/t/${esc(a.public_id)}?source=qr</code><button class="btn secondary small" data-qr="${a.public_id}">${tr('print')}</button></article>`).join('')}</div>`; }
function staffAudit(d){ return `${pageHead('Configuration & provenance',tr('audit'),'Administrative changes, scientific corrections and reviews remain traceable.')}<div class="table-card"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Detail</th></tr></thead><tbody>${d.audit.slice().reverse().map(a=>`<tr><td>${fmt(a.occurred_at)}</td><td>${esc(a.actor)}</td><td>${esc(human(a.action))}</td><td>${esc(a.entity_type)} · ${esc(a.entity_id)}</td><td class="wrap">${esc(a.detail||'')}</td></tr>`).join('')}</tbody></table></div>`; }
function staffSettings(){ return `${pageHead('Production readiness',tr('settings'),'Security and governance controls are treated as release gates, not optional documentation.')}<div class="settings-grid"><article><h2>Spatial security</h2><dl class="details"><div><dt>Latest public generalisation</dt><dd>${cfg.publicLatestGeneralisationMetres} m</dd></div><div><dt>Historical public generalisation</dt><dd>${cfg.publicHistoryGeneralisationMetres} m</dd></div><div><dt>Recent location delay</dt><dd>${cfg.publicLatestDelayHours} h</dd></div></dl></article><article><h2>Release gates</h2><ul class="gate-list"><li class="pending">⚑ ${tr('popiaGate')}</li><li class="pending">⚑ ${tr('penTestGate')}</li><li class="pending">⚑ ${tr('animalWelfareGate')}</li><li class="pending">⚑ ${tr('fieldTrialGate')}</li></ul></article><article><h2>Product telemetry</h2><p>Local privacy-safe UX events: <strong>${productEvents().length}</strong></p><p>No coordinates, names, emails or free-text observation notes are stored in product analytics.</p></article></div>`; }
function notFoundView(){ return `<section class="section narrow">${pageHead('404',tr('notFoundTitle'),tr('notFoundText'))}<a class="btn primary" href="#/">${tr('returnHome')}</a></section>`; }

async function render(){
  stopScanner(); const p=route(); let content='';
  try{
    if(p==='/')content=await homeView(); else if(p==='/identify')content=identifyView(); else if(p==='/scan')content=scanView(); else if(p==='/untagged')content=sightingView(null,true); else if(p==='/confirmation')content=confirmationView(); else if(p==='/map')content=await mapView(); else if(p==='/insights')content=await publicInsightsView(); else if(p==='/directory')content=await directoryView(); else if(p==='/about')content=aboutView(); else if(p==='/privacy')content=privacyView(); else if(p==='/login')content=loginView(); else if(p==='/logout'){authApi().logout();state.role=null;state.staffName=null;sessionStorage.removeItem('nautilus-role');sessionStorage.removeItem('nautilus-staff-name');content=await homeView();} else if(p.startsWith('/t/')){const src=query().get('source');sessionStorage.setItem('nautilus-identification-source',src==='qr'?'qr':'manual');content=await profileView(p.split('/')[2]);} else if(p.startsWith('/sighting/'))content=sightingView(p.split('/')[2],false); else if(p.startsWith('/staff/'))content=await staffView(p.split('/')[2]||'dashboard'); else content=notFoundView();
  }catch(err){ console.error(err); content=`<section class="section narrow"><div class="notice danger"><strong>${tr('applicationError')}</strong><p>${esc(err.message||String(err))}</p></div></section>`; }
  document.querySelector('#app').innerHTML=shell(content); bindShell(); document.querySelectorAll('[data-nav]').forEach(a=>{const active=p===a.dataset.nav||(a.dataset.nav==='/login'&&p.startsWith('/staff'));if(active)a.setAttribute('aria-current','page');}); document.title=`${document.querySelector('h1')?.textContent||tr('appName')} — Nautilus Bay`; await updateNetworkUI(); bindView(p); requestAnimationFrame(()=>{const h=document.querySelector('#main-content h1');if(h){h.setAttribute('tabindex','-1');h.focus({preventScroll:true});}else document.querySelector('#main-content')?.focus({preventScroll:true});});
}

function bindShell(){
  const lang=document.querySelector('#language-btn'); if(lang)lang.onclick=()=>{setLanguage(getLanguage()==='en'?'af':'en');haptic('light');render();};
  const more=document.querySelector('#app-more-button'),nav=document.querySelector('#mobile-menu'),scrim=document.querySelector('#mobile-menu-scrim'),closeBtn=document.querySelector('#mobile-menu-close');
  const setMenu=open=>{if(!nav)return;nav.hidden=!open;if(scrim)scrim.hidden=!open;if(more)more.setAttribute('aria-expanded',String(open));document.documentElement.classList.toggle('sheet-open',open);if(open)requestAnimationFrame(()=>closeBtn?.focus());};
  if(more)more.onclick=()=>setMenu(nav?.hidden!==false); if(closeBtn)closeBtn.onclick=()=>setMenu(false); if(scrim)scrim.onclick=()=>setMenu(false); nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
  const updateInstallButtons=()=>document.querySelectorAll('[data-install-button]').forEach(b=>b.toggleAttribute('hidden',!state.installPrompt||installState().installed));
  updateInstallButtons(); document.querySelectorAll('[data-install-button]').forEach(b=>b.addEventListener('click',async()=>{if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;updateInstallButtons();}}));
}

async function updateNetworkUI(){
  const slot=document.querySelector('#network-slot'),pill=document.querySelector('#pending-count-global'); const n=await countPending().catch(()=>0);
  if(!navigator.onLine)slot.innerHTML=`<div class="offline-banner">⚠ ${tr('offlineBanner')}</div>`; else slot.innerHTML='';
  if(n&&pill){pill.hidden=false;pill.innerHTML=`<span>${n} ${tr('pendingSync')}</span><button id="global-sync">${tr('syncNow')}</button>`;document.querySelector('#global-sync').onclick=doSync;} else if(pill)pill.hidden=true;
}

function bindView(p){
  if(p==='/identify')bindIdentify(); if(p==='/directory')bindDirectory(); if(p==='/scan')bindScanner(); if(p.startsWith('/t/'))bindProfileMap(p.split('/')[2]); if(p==='/map')bindMainMap(); if(p==='/untagged'||p.startsWith('/sighting/'))bindSighting(); if(p==='/login')bindLogin(); if(p.startsWith('/staff/'))bindStaff(p.split('/')[2]);
}
function bindIdentify(){ const f=document.querySelector('#identify-form'); f.onsubmit=async e=>{e.preventDefault();const id=document.querySelector('#tortoise-id').value.trim().toUpperCase();track('manual_id_selected');const a=await Repo.publicAnimal(id);if(a){sessionStorage.setItem('nautilus-identification-source','manual');go(`/t/${a.public_id}?source=manual`);}else document.querySelector('#identify-error').textContent=tr('notFound');}; }
function bindScanner(){ const b=document.querySelector('#scan-start'); if(b)b.onclick=startScanner; }
async function startScanner(){
  const status=document.querySelector('#scan-status'),stage=document.querySelector('#scanner-stage'); track('qr_scan_started');
  if(!('BarcodeDetector'in window)){status.textContent=tr('qrUnsupported');return;}
  try{state.qrStream=await getCameraStream({video:{facingMode:{ideal:'environment'}}});const video=document.createElement('video');video.autoplay=true;video.playsInline=true;video.srcObject=state.qrStream;stage.innerHTML='';stage.append(video);const detector=new BarcodeDetector({formats:['qr_code']});
    const detect=async()=>{if(!state.qrStream)return;try{const codes=await detector.detect(video);if(codes.length){const raw=codes[0].rawValue||'';const m=raw.match(/T\d{3,8}/i);if(m){const id=m[0].toUpperCase();const a=await Repo.publicAnimal(id);if(a){track('qr_scan_succeeded');haptic('medium');sessionStorage.setItem('nautilus-identification-source','qr');stopScanner();go(`/t/${id}?source=qr`);return;}status.textContent=`${tr('qrReadUnknown')} ${id}`;}}}catch{}setTimeout(detect,450);};detect();
  }catch(err){status.textContent=err.name==='NotAllowedError'?tr('cameraPermissionDenied'):err.message;}
}
function stopScanner(){if(state.qrStream){stopMediaStream(state.qrStream);state.qrStream=null;}}
async function bindProfileMap(publicId){
  const rows=await Repo.publicHistory(publicId),el=document.querySelector('#profile-map');
  if(el){try{const {renderMap}=await import('./map.js');await renderMap(el,rows);}catch{el.innerHTML=`<div class="map-fallback">${tr('mapUnavailable')}</div>`;}}
  document.querySelector('[data-share-profile]')?.addEventListener('click',async()=>{const a=await Repo.publicAnimal(publicId);const ok=await share({title:`${a?.name||publicId} — ${tr('appName')}`,text:tr('shareProfile'),url:`${cfg.siteUrl.replace(/\/$/,'')}/#/t/${publicId}`});if(!ok)toast(tr('shareUnavailable'));else haptic('light');});
}

async function bindMainMap(){
  const [raw,animals]=await Promise.all([Repo.publicMap(),Repo.publicAnimals()]);const byId=new Map(animals.map(a=>[a.public_id,a]));const all=raw.map(r=>{const a=byId.get(r.public_id)||{};return {...r,species_name:getLanguage()==='af'?(a.common_name_af||a.common_name_en):(a.common_name_en||a.common_name_af)};});
  const el=document.querySelector('#main-map'),animal=document.querySelector('#map-filter'),theme=document.querySelector('#map-theme'),from=document.querySelector('#map-from'),to=document.querySelector('#map-to'),cell=document.querySelector('#map-cell-size'),densityWrap=document.querySelector('#public-density-size'),summary=document.querySelector('#public-map-summary'),list=document.querySelector('#public-map-list');
  async function draw(){const rows=applyObservationFilters(all,{animal:animal.value,from:from.value,to:to.value});densityWrap.hidden=theme.value!=='density';summary.innerHTML=`<span><strong>${rows.length}</strong> ${tr('filteredObservations')}</span><span><strong>${new Set(rows.map(r=>r.public_id).filter(Boolean)).size}</strong> ${tr('uniqueAnimals')}</span>`;list.innerHTML=accessibleObservationList(rows);el.innerHTML=`<div class="map-loader">${tr('loadingMap')}</div>`;try{const {renderThematicMap}=await import('./map.js');await renderThematicMap(el,rows,{theme:theme.value,publicMode:true,densityCellMetres:Number(cell.value),legendTitle:tr('theme')});}catch{el.innerHTML=`<div class="map-fallback">${tr('mapUnavailable')}</div>`;}}
  [animal,theme,from,to,cell].forEach(x=>x?.addEventListener('change',draw));document.querySelector('#map-clear')?.addEventListener('click',()=>{animal.value='all';theme.value='species';from.value='';to.value='';cell.value='500';draw();});draw();
}

function bindChoiceGroups(){ document.querySelectorAll('[data-choice]').forEach(group=>group.addEventListener('click',e=>{const b=e.target.closest('.choice');if(!b)return;group.querySelectorAll('.choice').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false');});b.classList.add('selected');b.setAttribute('aria-pressed','true');updateQualityPreview();})); }
function chosen(name){return document.querySelector(`[data-choice="${name}"] .choice.selected`)?.dataset.value||'';}
function bindSighting(){
  bindChoiceGroups(); initTurnstile(); const gps=document.querySelector('#gps-button'),photos=document.querySelector('#photos'),form=document.querySelector('#sighting-form');
  gps.onclick=captureGps; photos.onchange=handlePhotos; form.onsubmit=submitSighting;
  state.sightingStep=1; setSightingStep(1);
  document.querySelectorAll('[data-next-step]').forEach(b=>b.onclick=()=>advanceSighting(Number(b.dataset.nextStep)));
  document.querySelectorAll('[data-prev-step]').forEach(b=>b.onclick=()=>setSightingStep(Number(b.dataset.prevStep)));
  form.addEventListener('input',saveSightingDraft); form.addEventListener('click',e=>{if(e.target.closest('.choice')){saveSightingDraft();updateConditionAlert();}});
  restoreSightingDraft(); updateConditionAlert();
  track('sighting_started',{untagged:form.dataset.untagged==='true'}); updateQualityPreview();
}
function setSightingStep(step){ state.sightingStep=step; document.querySelectorAll('[data-flow-step]').forEach(el=>el.hidden=Number(el.dataset.flowStep)!==step);document.querySelectorAll('.progress [data-step]').forEach(el=>{const active=Number(el.dataset.step)===step;el.classList.toggle('active',active);active?el.setAttribute('aria-current','step'):el.removeAttribute('aria-current');});document.querySelector(`[data-flow-step="${step}"] h2`)?.focus?.({preventScroll:true});window.scrollTo({top:Math.max(0,(document.querySelector('.sighting-flow')?.offsetTop||0)-80),behavior:'smooth'});}
function advanceSighting(step){ const err=document.querySelector('#submit-error'); if(err)err.textContent='';if(step===2&&!Number(document.querySelector('#accuracy')?.value)){toast(tr('gpsBeforeContinue'),'error');return;}if(step===3&&(document.querySelector('#photos')?._compressed||[]).length<1){toast(tr('photoRequired'),'error');return;}setSightingStep(step);if(step===4)updateQualityPreview();}
function saveSightingDraft(){const form=document.querySelector('#sighting-form');if(!form)return;const draft={public_id:form.dataset.publicId||null,untagged:form.dataset.untagged==='true',identification_confidence:chosen('identification_confidence'),behaviour:chosen('behaviour'),condition:chosen('condition'),notes:document.querySelector('#notes')?.value||'',possible_species:document.querySelector('#possible-species')?.value||'',step:state.sightingStep};sessionStorage.setItem('nautilus-sighting-draft',JSON.stringify(draft));}
function restoreSightingDraft(){try{const d=JSON.parse(sessionStorage.getItem('nautilus-sighting-draft')||'null');const form=document.querySelector('#sighting-form');if(!d||!form||d.public_id!==(form.dataset.publicId||null)||d.untagged!==(form.dataset.untagged==='true'))return;for(const [group,val] of [['identification_confidence',d.identification_confidence],['behaviour',d.behaviour],['condition',d.condition]]){if(!val)continue;const root=document.querySelector(`[data-choice="${group}"]`);root?.querySelectorAll('.choice').forEach(x=>{const on=x.dataset.value===val;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',String(on));});}if(document.querySelector('#notes'))document.querySelector('#notes').value=d.notes||'';if(document.querySelector('#possible-species'))document.querySelector('#possible-species').value=d.possible_species||'';}catch{}}
function updateConditionAlert(){const el=document.querySelector('#condition-alert');if(!el)return;const c=chosen('condition');const alerting=['possible_injury','shell_damage','unusual','dead'].includes(c);el.hidden=!alerting;if(alerting)el.innerHTML=`<strong>${tr('healthAlertTitle')}</strong><p>${c==='dead'?tr('deadGuidance'):tr('injuryGuidance')}</p>`;}


async function initTurnstile(){
  const container=document.querySelector('#turnstile-widget'); if(!container||!cfg.turnstileSiteKey)return;
  try{
    if(!window.turnstile){ await new Promise((resolve,reject)=>{ const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.defer=true;s.onload=resolve;s.onerror=reject;document.head.append(s); }); }
    window.turnstile.render(container,{sitekey:cfg.turnstileSiteKey,theme:'light',action:'public_sighting',callback:token=>{document.querySelector('#sighting-form').dataset.turnstileToken=token;},'expired-callback':()=>{document.querySelector('#sighting-form').dataset.turnstileToken='';}});
  }catch(e){console.warn('Turnstile unavailable',e);}
}

async function captureGps(){
  track('gps_permission_prompted'); const b=document.querySelector('#gps-button'),status=document.querySelector('#gps-status'); b.disabled=true;status.innerHTML=`<span class="status-dot neutral"></span><strong>${tr('acquiringGps')}</strong>`;
  try{const pos=await getCurrentPosition({enableHighAccuracy:true,timeout:15000,maximumAge:0});const {latitude,longitude,accuracy}=pos.coords;document.querySelector('#lat').value=latitude;document.querySelector('#lng').value=longitude;document.querySelector('#accuracy').value=accuracy;const poor=accuracy>cfg.gpsWarningMetres;status.innerHTML=`<span class="status-dot ${poor?'warn':'good'}"></span><strong>${poor?tr('gpsPoor'):tr('gpsCaptured')}</strong><span>${tr('accuracy')} ±${Math.round(accuracy)} m</span>`;b.textContent=tr('retryGps');b.disabled=false;haptic(poor?'light':'medium');track('gps_captured',{accuracy_band:accuracy<=25?'excellent':accuracy<=50?'good':accuracy<=100?'weak':'poor'});updateQualityPreview();}
  catch(err){status.innerHTML=`<span class="status-dot bad"></span><strong>${err.name==='NotSupportedError'?tr('geolocationUnavailable'):esc(err.message||tr('geolocationUnavailable'))}</strong>`;b.disabled=false;track('gps_failed',{code:err.code||0});}
}

async function compressImage(file){
  const bitmap=await createImageBitmap(file);const max=cfg.compressedPhotoMaxDimension;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const w=Math.round(bitmap.width*scale),h=Math.round(bitmap.height*scale);const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(bitmap,0,0,w,h);bitmap.close?.();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',cfg.compressedPhotoQuality));return {blob,type:'image/jpeg',width:w,height:h,original_name:file.name};
}
async function handlePhotos(e){ const input=e.target,preview=document.querySelector('#photo-previews');preview.innerHTML='';const files=[...input.files].slice(0,cfg.maxPhotos);input._compressed=[];for(const file of files){if(file.size>cfg.maxPhotoBytes*4){toast('Photo is too large to process.','error');continue;}try{const p=await compressImage(file);input._compressed.push(p);const url=URL.createObjectURL(p.blob);const fig=document.createElement('figure');fig.innerHTML=`<img alt="Tortoise sighting preview" src="${url}"><figcaption>${Math.round(p.blob.size/1024)} KB</figcaption>`;preview.append(fig);track('photo_added',{compressed_kb:Math.round(p.blob.size/1024)});}catch(err){toast(err.message,'error');}} updateQualityPreview(); }
function formDraft(){ const form=document.querySelector('#sighting-form');return {client_submission_id:form.dataset.clientId||uuid(),public_id:form.dataset.publicId||null,animal_id:isDemo()&&form.dataset.publicId?DemoDB.animalByPublicId(form.dataset.publicId)?.id:null,observed_at:new Date().toISOString(),lat:Number(document.querySelector('#lat').value),lng:Number(document.querySelector('#lng').value),accuracy_m:Number(document.querySelector('#accuracy').value),identification_method:form.dataset.source||'manual',identification_confidence:chosen('identification_confidence')||'certain',behaviour:chosen('behaviour')||'unknown',condition:chosen('condition')||'healthy',notes:document.querySelector('#notes').value.trim(),possible_species:document.querySelector('#possible-species')?.value||null,turnstile_token:form.dataset.turnstileToken||null,photos:document.querySelector('#photos')._compressed||[]}; }
function updateQualityPreview(){ const el=document.querySelector('#quality-preview');if(!el)return;const d=formDraft();const score=qualityScore(d);el.innerHTML=`<span class="score ${qualityBand(score)}">${score}</span><div><strong>${tr('quality')} ${score}/100</strong><small>${tr('qualityExplain')}</small></div>`; }
async function submitSighting(e){ e.preventDefault();const err=document.querySelector('#submit-error'),btn=document.querySelector('#submit-sighting');err.textContent='';const row=formDraft();if(!Number.isFinite(row.lat)||!Number.isFinite(row.lng)||!row.accuracy_m){err.textContent=tr('gpsUnavailable');return;}if(row.accuracy_m>cfg.gpsRejectMetres){err.textContent=`${tr('gpsTooWeak')} ±${Math.round(row.accuracy_m)} m. ${tr('retryBeforeSubmit')}`;return;}if(row.photos.length<1){err.textContent=tr('photoRequired');return;}row.quality_score=qualityScore(row);btn.disabled=true;btn.textContent=tr('saving');try{if(!navigator.onLine){row.turnstile_token=null;await queueSighting(row);row.queued=true;track('sighting_queued',{quality_band:qualityBand(row.quality_score)});}else{await Repo.submitPublicSighting(row);row.queued=false;track('sighting_completed',{quality_band:qualityBand(row.quality_score),condition:row.condition,identification_method:row.identification_method});}state.lastSubmission={...row,photos:undefined};sessionStorage.setItem('nautilus-last-submission',JSON.stringify(state.lastSubmission));sessionStorage.removeItem('nautilus-sighting-draft');go('/confirmation');}catch(ex){try{row.turnstile_token=null;await queueSighting(row);row.queued=true;state.lastSubmission={...row,photos:undefined};sessionStorage.setItem('nautilus-last-submission',JSON.stringify(state.lastSubmission));sessionStorage.removeItem('nautilus-sighting-draft');track('sighting_queued',{reason:'submit_failure'});go('/confirmation');}catch(q){err.textContent=q.message||ex.message;btn.disabled=false;btn.textContent=tr('submit');}} }
async function doSync(){ if(!navigator.onLine)return;const r=await syncPending(row=>Repo.submitPublicSighting(row));if(r.failed){track('sync_failed',{failed:r.failed});toast(tr('syncFailed'),'error');}else{track('sync_succeeded',{sent:r.sent});toast(tr('allSynced'));}updateNetworkUI(); }

function bindLogin(){
  document.querySelectorAll('[data-demo-role]').forEach(b=>b.onclick=()=>{const role=b.dataset.demoRole;state.role=role;state.staffName=`${human(role)} Demo`;sessionStorage.setItem('nautilus-role',role);sessionStorage.setItem('nautilus-staff-name',state.staffName);track('staff_login',{role,demo:true});go('/staff/dashboard');});
  const form=document.querySelector('#login-form');if(form)form.onsubmit=async e=>{e.preventDefault();const err=document.querySelector('#login-error');try{await authApi().login(document.querySelector('#login-email').value,document.querySelector('#login-password').value);const profile=await authApi().profile();if(!profile?.active)throw new Error('This staff account is inactive.');state.role=profile.role;state.staffName=profile.display_name||profile.role;sessionStorage.setItem('nautilus-role',state.role);sessionStorage.setItem('nautilus-staff-name',state.staffName);if(state.role==='admin'&&authApi().aal()!=='aal2'){const factors=await authApi().listFactors();const verified=(factors?.totp||factors?.all||[]).find(f=>f.status==='verified');if(!verified)throw new Error('Administrator MFA is mandatory. Enrol a verified TOTP factor before using the administration console.');const ch=await authApi().challengeFactor(verified.id);document.querySelector('#app').innerHTML=shell(mfaView(verified.id,ch.id));bindShell();bindMfa();return;}track('staff_login',{role:state.role,demo:false});go('/staff/dashboard');}catch(ex){err.textContent=ex.message;}};
}
function bindMfa(){const f=document.querySelector('#mfa-form');f.onsubmit=async e=>{e.preventDefault();const err=document.querySelector('#mfa-error');try{await authApi().verifyFactor(f.dataset.factor,f.dataset.challenge,document.querySelector('#mfa-code').value.trim());if(authApi().aal()!=='aal2')throw new Error('MFA verification did not elevate the session to AAL2.');go('/staff/dashboard');}catch(ex){err.textContent=ex.message;}};}

function bindStaff(section){
  if(section==='spatial')bindStaffSpatial(); if(section==='animals')bindStaffAnimals(); if(section==='observations')bindStaffObservations(); if(section==='health')bindStaffHealth(); if(section==='research')bindResearch(); if(section==='export')bindExports(); if(section==='qr')bindQr();
}

async function bindStaffSpatial(){
  const d=await Repo.staffSnapshot(),all=enrichStaffRows(d);const els={animal:document.querySelector('#spatial-animal'),species:document.querySelector('#spatial-species'),condition:document.querySelector('#spatial-condition'),verification:document.querySelector('#spatial-verification'),from:document.querySelector('#spatial-from'),to:document.querySelector('#spatial-to'),theme:document.querySelector('#spatial-theme'),cell:document.querySelector('#spatial-cell'),accuracy:document.querySelector('#spatial-accuracy'),density:document.querySelector('#spatial-density-wrap'),map:document.querySelector('#staff-map'),summary:document.querySelector('#spatial-summary'),table:document.querySelector('#spatial-table')};let current=[];
  const draw=async()=>{current=applyObservationFilters(all,{animal:els.animal.value,species:els.species.value,condition:els.condition.value,verification:els.verification.value,from:els.from.value,to:els.to.value});els.density.hidden=els.theme.value!=='density';const med=median(current.map(x=>x.accuracy_m));const dates=current.map(x=>new Date(x.observed_at)).filter(x=>!Number.isNaN(x.getTime())).sort((a,b)=>a-b);els.summary.innerHTML=`<span><strong>${current.length}</strong> ${tr('filteredObservations')}</span><span><strong>${new Set(current.map(x=>x.public_id).filter(Boolean)).size}</strong> ${tr('uniqueAnimals')}</span><span><strong>${med==null?'—':Math.round(med)+' m'}</strong> ${tr('medianGpsAccuracy')}</span><span><strong>${dates.length?fmtDate(dates[0])+' → '+fmtDate(dates.at(-1)):'—'}</strong> ${tr('dateSpan')}</span>`;els.table.innerHTML=current.length?`<table><thead><tr><th>Date</th><th>Animal</th><th>${tr('species')}</th><th>${tr('condition')}</th><th>GPS</th><th>${tr('quality')}</th><th>${tr('verification')}</th></tr></thead><tbody>${current.slice().sort((a,b)=>new Date(b.observed_at)-new Date(a.observed_at)).map(o=>`<tr><td>${fmt(o.observed_at)}</td><td>${esc(o.public_id||'UNTAGGED')}</td><td>${esc(o.species_name||'—')}</td><td>${human(o.condition||'unknown')}</td><td>±${Math.round(o.accuracy_m||0)} m</td><td>${o.quality_score??'—'}</td><td>${human(o.verification_status||'—')}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">${tr('noDataFilter')}</div>`;els.map.innerHTML=`<div class="map-loader">${tr('loadingMap')}</div>`;try{const {renderThematicMap}=await import('./map.js');await renderThematicMap(els.map,current,{theme:els.theme.value,showAccuracy:els.accuracy.checked,densityCellMetres:Number(els.cell.value),enableMeasure:true,publicMode:false,connectPoints:false,legendTitle:tr('theme')});}catch(ex){console.error(ex);els.map.innerHTML=`<div class="map-fallback">${tr('mapUnavailable')}</div>`;}};
  Object.values(els).forEach(x=>{if(x instanceof HTMLSelectElement||x instanceof HTMLInputElement)x.addEventListener('change',draw);});document.querySelector('#spatial-clear')?.addEventListener('click',()=>{els.animal.value='all';els.species.value='';els.condition.value='';els.verification.value='';els.from.value='';els.to.value='';els.theme.value='species';els.cell.value='250';els.accuracy.checked=false;draw();});document.querySelectorAll('[data-spatial-export]').forEach(b=>b.onclick=()=>{const kind=b.dataset.spatialExport,stamp=new Date().toISOString().slice(0,10);if(kind==='kml')downloadText(`nautilus-map-${stamp}.kml`,observationsKML(current),'application/vnd.google-earth.kml+xml');if(kind==='kml-connections')downloadText(`nautilus-map-connections-${stamp}.kml`,movementKML(current),'application/vnd.google-earth.kml+xml');if(kind==='geojson')downloadText(`nautilus-map-${stamp}.geojson`,observationsGeoJSON(current),'application/geo+json');if(kind==='csv')downloadText(`nautilus-map-${stamp}.csv`,observationCSV(current),'text/csv');track('export_created',{kind:'spatial_'+kind,count:current.length});});draw();
}
async function bindStaffAnimals(){
  let data=await Repo.staffSnapshot();const search=document.querySelector('#animal-search');if(search)search.oninput=()=>document.querySelector('#animal-table').innerHTML=animalRows(data,search.value);
  document.querySelector('#add-animal')?.addEventListener('click',()=>animalDialog(data));document.querySelectorAll('[data-edit-animal]').forEach(b=>b.onclick=()=>animalDialog(data,data.animals.find(a=>a.id===b.dataset.editAnimal)));
}
function animalDialog(data,a=null){ const root=modal(`<div class="dialog-head"><div><span class="eyebrow">Animal registry</span><h2>${a?tr('editAnimal'):tr('addAnimal')}</h2></div><button class="close" data-close aria-label="Close">×</button></div><form id="animal-form"><div class="form-grid"><label class="field"><span>${tr('publicId')}</span><input id="animal-public-id" value="${esc(a?.public_id||'')}" ${a?'readonly':''} required pattern="T[0-9]{3,8}"></label><label class="field"><span>${tr('name')}</span><input id="animal-name" value="${esc(a?.name||'')}"></label><label class="field"><span>${tr('species')}</span><select id="animal-taxon">${data.taxa.map(t=>`<option value="${t.id}" ${a?.taxon_id===t.id?'selected':''}>${esc(t.common_name_en)} — ${esc(t.scientific_name)}</option>`).join('')}</select></label><label class="field"><span>${tr('sex')}</span><select id="animal-sex">${['unknown','female','male'].map(x=>`<option ${a?.sex===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field"><span>Sex confidence</span><select id="animal-sex-confidence">${['unknown','low','medium','high','confirmed'].map(x=>`<option ${a?.sex_confidence===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field"><span>${tr('lifeStage')}</span><select id="animal-life"><option>unknown</option><option ${a?.life_stage==='juvenile'?'selected':''}>juvenile</option><option ${a?.life_stage==='subadult'?'selected':''}>subadult</option><option ${a?.life_stage==='adult'?'selected':''}>adult</option></select></label><label class="field"><span>${tr('approxAge')}</span><input id="animal-age" type="number" min="0" step="0.5" value="${esc(a?.estimated_age_years??'')}"></label><label class="field"><span>Age estimation method</span><input id="animal-age-method" value="${esc(a?.age_estimation_method||'')}"></label></div><label class="field"><span>${tr('distinguishing')}</span><textarea id="animal-features">${esc(a?.identifying_features||'')}</textarea></label><div class="dialog-actions"><button type="button" class="btn secondary" data-close>${tr('cancel')}</button><button class="btn primary">${tr('save')}</button></div><div id="animal-error" class="form-error"></div></form>`);
  root.querySelector('#animal-form').onsubmit=async e=>{e.preventDefault();const row={public_id:root.querySelector('#animal-public-id').value.trim().toUpperCase(),name:root.querySelector('#animal-name').value.trim(),taxon_id:root.querySelector('#animal-taxon').value,sex:root.querySelector('#animal-sex').value,sex_confidence:root.querySelector('#animal-sex-confidence').value,life_stage:root.querySelector('#animal-life').value,estimated_age_years:Number(root.querySelector('#animal-age').value)||null,age_estimation_method:root.querySelector('#animal-age-method').value.trim()||null,identifying_features:root.querySelector('#animal-features').value.trim()};try{a?await Repo.updateAnimal(a.id,row,state.staffName):await Repo.createAnimal(row,state.staffName);root.innerHTML='';toast(tr('save'));render();}catch(ex){root.querySelector('#animal-error').textContent=ex.message;}};
}
function bindStaffObservations(){
  document.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{const reason=prompt('Review rationale / evidence:');if(!reason)return;await Repo.reviewObservation(b.dataset.review,b.dataset.status,reason,state.staffName);toast('Review appended');render();});
  document.querySelectorAll('[data-correct]').forEach(b=>b.onclick=()=>correctionDialog(b.dataset.correct));
}
function correctionDialog(id){ const root=modal(`<div class="dialog-head"><div><span class="eyebrow">Scientific correction</span><h2>${tr('correct')}</h2></div><button class="close" data-close>×</button></div><p class="notice info">${tr('immutable')}</p><form id="correction-form"><label class="field"><span>${tr('correctionReason')}</span><textarea id="correction-reason" required></textarea></label><div class="form-grid"><label class="field"><span>Corrected condition (optional)</span><select id="correct-condition"><option value="">No change</option><option value="healthy">Healthy</option><option value="possible_injury">Possible injury</option><option value="shell_damage">Shell damage</option><option value="unsure">Unsure</option></select></label><label class="field"><span>Corrected timestamp (optional)</span><input type="datetime-local" id="correct-time"></label></div><div class="dialog-actions"><button type="button" class="btn secondary" data-close>${tr('cancel')}</button><button class="btn primary">Append correction</button></div></form>`);root.querySelector('#correction-form').onsubmit=async e=>{e.preventDefault();const changes={};const condition=root.querySelector('#correct-condition').value,time=root.querySelector('#correct-time').value;if(condition)changes.condition=condition;if(time)changes.observed_at=new Date(time).toISOString();await Repo.correctObservation(id,changes,root.querySelector('#correction-reason').value.trim(),state.staffName);root.innerHTML='';toast('Correction appended');render();}; }
function bindStaffHealth(){ document.querySelector('#new-health-case')?.addEventListener('click',healthDialog);document.querySelectorAll('[data-health-update]').forEach(b=>b.onclick=()=>healthUpdateDialog(b.dataset.healthUpdate));document.querySelectorAll('[data-health-event]').forEach(b=>b.onclick=()=>healthEventDialog(b.dataset.healthEvent)); }
async function healthDialog(){const d=await Repo.staffSnapshot();const root=modal(`<div class="dialog-head"><h2>${tr('newHealthCase')}</h2><button class="close" data-close>×</button></div><form id="health-form"><label class="field"><span>Animal</span><select id="health-animal">${d.animals.map(a=>`<option value="${a.id}">${a.public_id} — ${esc(a.name||'')}</option>`).join('')}</select></label><label class="field"><span>${tr('severity')}</span><select id="health-severity"><option>low</option><option selected>moderate</option><option>high</option><option>critical</option></select></label><label class="field"><span>Summary</span><textarea id="health-summary" required></textarea></label><label class="field"><span>${tr('assignedTo')}</span><input id="health-assigned" value="Conservation Team"></label><div class="dialog-actions"><button type="button" class="btn secondary" data-close>${tr('cancel')}</button><button class="btn primary">${tr('save')}</button></div></form>`);root.querySelector('#health-form').onsubmit=async e=>{e.preventDefault();await Repo.createHealthCase({animal_id:root.querySelector('#health-animal').value,severity:root.querySelector('#health-severity').value,summary:root.querySelector('#health-summary').value.trim(),assigned_to:root.querySelector('#health-assigned').value.trim()},state.staffName);root.innerHTML='';toast('Health case created');render();};}
async function healthUpdateDialog(id){const root=modal(`<div class="dialog-head"><h2>Update health case</h2><button class="close" data-close>×</button></div><form id="health-update"><label class="field"><span>${tr('status')}</span><select id="case-status"><option>open</option><option>monitoring</option><option>closed</option></select></label><label class="field"><span>${tr('followUp')}</span><input id="case-follow" type="date"></label><label class="field"><span>${tr('outcome')}</span><textarea id="case-outcome"></textarea></label><div class="dialog-actions"><button type="button" class="btn secondary" data-close>${tr('cancel')}</button><button class="btn primary">${tr('save')}</button></div></form>`);root.querySelector('#health-update').onsubmit=async e=>{e.preventDefault();await Repo.updateHealthCase(id,{status:root.querySelector('#case-status').value,follow_up_date:root.querySelector('#case-follow').value||null,outcome:root.querySelector('#case-outcome').value.trim()||null},state.staffName);root.innerHTML='';toast('Health case updated');render();};}

async function healthEventDialog(id){
  const root=modal(`<div class="dialog-head"><h2>Clinical health event</h2><button class="close" data-close>×</button></div><form id="health-event-form"><div class="form-grid"><label class="field"><span>Event type</span><select id="he-type"><option>assessment</option><option>triage</option><option>treatment</option><option>referral</option><option>follow_up</option><option>note</option></select></label><label class="field"><span>Injury type</span><input id="he-injury"></label><label class="field"><span>Body location</span><input id="he-body"></label><label class="field"><span>Shell fracture</span><select id="he-fracture"><option value="">Unknown</option><option value="false">No</option><option value="true">Yes</option></select></label><label class="field"><span>Mobility</span><input id="he-mobility"></label><label class="field"><span>Body condition</span><input id="he-condition"></label></div><label class="field"><span>Clinical notes</span><textarea id="he-notes"></textarea></label><label class="field"><span>Treatment / action</span><textarea id="he-treatment"></textarea></label><div class="dialog-actions"><button type="button" class="btn secondary" data-close>${tr('cancel')}</button><button class="btn primary">${tr('save')}</button></div></form>`);
  root.querySelector('#health-event-form').onsubmit=async e=>{e.preventDefault();const f=root.querySelector('#he-fracture').value;await Repo.addHealthEvent({health_case_id:id,event_type:root.querySelector('#he-type').value,injury_type:root.querySelector('#he-injury').value.trim()||null,body_location:root.querySelector('#he-body').value.trim()||null,shell_fracture:f===''?null:f==='true',mobility:root.querySelector('#he-mobility').value.trim()||null,body_condition:root.querySelector('#he-condition').value.trim()||null,clinical_notes:root.querySelector('#he-notes').value.trim()||null,treatment:root.querySelector('#he-treatment').value.trim()||null},state.staffName);root.innerHTML='';toast('Clinical event saved');render();};
}

async function bindResearch(){document.querySelector('#add-measurement')?.addEventListener('click',async()=>{const d=await Repo.staffSnapshot();const root=modal(`<div class="dialog-head"><h2>${tr('addMeasurement')}</h2><button class="close" data-close>×</button></div><form id="measurement-form"><label class="field"><span>Animal</span><select id="measurement-animal">${d.animals.map(a=>`<option value="${a.id}">${a.public_id} — ${esc(a.name||'')}</option>`).join('')}</select></label><div class="form-grid"><label class="field"><span>${tr('measurementType')}</span><select id="measurement-type"><option value="mass">Mass</option><option value="straight_carapace_length">Straight carapace length</option><option value="carapace_width">Carapace width</option></select></label><label class="field"><span>${tr('value')}</span><input id="measurement-value" type="number" step="0.01" required></label><label class="field"><span>${tr('unit')}</span><select id="measurement-unit"><option>kg</option><option>g</option><option>mm</option><option>cm</option></select></label><label class="field"><span>${tr('confidence')}</span><select id="measurement-confidence"><option>high</option><option>medium</option><option>low</option></select></label></div><label class="field"><span>${tr('method')}</span><input id="measurement-method" required></label><div class="dialog-actions"><button type="button" class="btn secondary" data-close>${tr('cancel')}</button><button class="btn primary">${tr('save')}</button></div></form>`);root.querySelector('#measurement-form').onsubmit=async e=>{e.preventDefault();await Repo.addMeasurement({animal_id:root.querySelector('#measurement-animal').value,measurement_type:root.querySelector('#measurement-type').value,value:Number(root.querySelector('#measurement-value').value),unit:root.querySelector('#measurement-unit').value,confidence:root.querySelector('#measurement-confidence').value,method:root.querySelector('#measurement-method').value.trim()},state.staffName);root.innerHTML='';toast('Measurement saved');render();};});}
async function bindExports(){const d=await Repo.staffSnapshot(),rows=enrichStaffRows(d);document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{const kind=b.dataset.export;if(kind==='registry')downloadText('nautilus-animal-registry.csv',registryCSV(d.animals,d.taxa),'text/csv');if(kind==='observations-csv')downloadText('nautilus-observations.csv',observationCSV(rows),'text/csv');if(kind==='geojson')downloadText('nautilus-observations.geojson',observationsGeoJSON(rows),'application/geo+json');if(kind==='kml')downloadText('nautilus-observations.kml',observationsKML(rows),'application/vnd.google-earth.kml+xml');if(kind==='movebank')downloadText('nautilus-movebank-events.csv',movebankEventCSV(rows,d.animals),'text/csv');track('export_created',{kind});});}
function bindQr(){document.querySelectorAll('[data-qr]').forEach(b=>b.onclick=async()=>{const id=b.dataset.qr,url=`${cfg.siteUrl.replace(/\/$/,'')}/#/t/${id}?source=qr`;if(isDemo()){const win=open('','_blank');win.document.write(`<title>${id} QR hand-off</title><style>body{font-family:sans-serif;max-width:700px;margin:4rem auto;padding:2rem}code{display:block;padding:1rem;background:#eee;word-break:break-all}</style><h1>${id}</h1><p>Production uses the self-hosted <code>qr-svg</code> Edge Function. Configure Supabase to render the actual QR SVG.</p><code>${esc(url)}</code>`);return;}try{const svg=await authApi().qrSvg(id);const blob=new Blob([svg],{type:'image/svg+xml'});open(URL.createObjectURL(blob),'_blank');}catch(ex){toast(ex.message,'error');}});}

let swReloading=false;
function showAppUpdate(reg){const slot=document.querySelector('#update-slot');if(!slot)return;slot.hidden=false;slot.innerHTML=`<div class="update-banner"><span><strong>${tr('updateAvailable')}</strong> ${tr('updateReadyText')}</span><button id="apply-update" class="btn small primary">${tr('refresh')}</button></div>`;document.querySelector('#apply-update')?.addEventListener('click',()=>{const waiting=reg.waiting;if(waiting)waiting.postMessage('SKIP_WAITING');else location.reload();});}
window.addEventListener('hashchange',()=>{haptic('light');render();});window.addEventListener('online',()=>{updateNetworkUI();doSync();});window.addEventListener('offline',updateNetworkUI);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;document.querySelectorAll('[data-install-button]').forEach(b=>b.removeAttribute('hidden'));});window.addEventListener('appinstalled',()=>{state.installPrompt=null;applyPlatformMode();document.querySelectorAll('[data-install-button]').forEach(b=>b.setAttribute('hidden',''));track('app_installed');});
setupNativeBack({canGoBack:()=>route()!=='/',onBack:()=>{if(history.length>1)history.back();else go('/');}});
if('serviceWorker'in navigator && !platform.native){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(swReloading)return;swReloading=true;location.reload();});navigator.serviceWorker.register('./service-worker.js').then(reg=>{if(reg.waiting&&navigator.serviceWorker.controller)showAppUpdate(reg);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)showAppUpdate(reg);});});setTimeout(()=>reg.update().catch(()=>{}),2500);}).catch(console.error);}
render();
