function csvCell(v){ const s=v==null?'':String(v); return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s; }
export function toCSV(rows,columns){ return [columns.join(','),...rows.map(r=>columns.map(c=>csvCell(r[c])).join(','))].join('\n'); }
export function registryCSV(animals,taxa){ return toCSV(animals.map(a=>{ const t=taxa.find(x=>x.id===a.taxon_id)||{}; return {public_id:a.public_id,name:a.name,scientific_name:t.scientific_name||'',common_name:t.common_name_en||'',sex:a.sex,life_stage:a.life_stage,estimated_age_years:a.estimated_age_years,registration_date:a.registration_date,status:a.status}; }),['public_id','name','scientific_name','common_name','sex','life_stage','estimated_age_years','registration_date','status']); }
export function observationsGeoJSON(observations){ return JSON.stringify({type:'FeatureCollection',features:observations.map(o=>({type:'Feature',geometry:{type:'Point',coordinates:[o.lng,o.lat]},properties:{id:o.id,animal_id:o.animal_id,public_id:o.public_id,observed_at:o.observed_at,accuracy_m:o.accuracy_m,behaviour:o.behaviour,condition:o.condition,verification_status:o.verification_status,quality_score:o.quality_score}}))},null,2); }
export function movebankEventCSV(observations,animals){
  const rows=observations.map(o=>{ const a=animals.find(x=>x.id===o.animal_id); return {'event-id':o.id,'individual-local-identifier':a?.public_id||o.public_id||'UNASSIGNED',timestamp:o.observed_at,'location-long':o.lng,'location-lat':o.lat,'sensor-type':'human observation','horizontal-accuracy':o.accuracy_m,'comments':`${o.behaviour||''}; ${o.condition||''}`}; });
  return toCSV(rows,['event-id','individual-local-identifier','timestamp','location-long','location-lat','sensor-type','horizontal-accuracy','comments']);
}
export function downloadText(filename,text,type='text/plain'){ const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
